'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EvaluationPage2
    
    '''<summary>
    '''ScriptManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerMain As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''pnlEvaluate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEvaluate As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rowEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowEdit As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblReadOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReadOnly As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''trHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trHead As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdColLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdColLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblColLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColLeft As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tdTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdTask As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''divEditTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEditTask As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadToolTipHints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipHints As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''RadToolTipClusterSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipClusterSteps As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''lblTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTask As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdColRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdColRight As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblColRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColRight As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''trContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContent As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdContent As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdMainCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMainCell As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''divLocalResultsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocalResultsHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEditTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEditTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadToolTipTitleHints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipTitleHints As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''RadToolTipTitleSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipTitleSteps As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''lblResultsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultsTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActionContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionContent As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''tdExtraContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdExtraContent As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''divSpyron control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSpyron As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SurveySpyron control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveySpyron As Global.Spyron_Surveys_ctrlSurveyPageView
    
    '''<summary>
    '''pnlSLResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSLResults As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptBlock As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadPaneGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPaneGrid As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''divGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divActiveView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divActiveView As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommand As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divExpectedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExpectedValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divObjectivesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divObjectivesData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divStepsData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStepsData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divClipData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClipData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlPleaseWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlPleaseWait As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPleaseWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPleaseWait As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlPrioritiesDerived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlPrioritiesDerived As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridResults As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblExpectedValueLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpectedValueLocal As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlQueryWhatsWrong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlQueryWhatsWrong As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlInconsistencyTooHigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlInconsistencyTooHigh As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlInsufficiencyOfData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlInsufficiencyOfData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctrlReviewJudgments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlReviewJudgments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tblHTMLResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHTMLResults As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''placeResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeResults As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''trGoalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGoalText As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdGoalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdGoalText As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''isChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isChanged As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnlNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNavigation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgNavHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNavHelp As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''cStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cStep As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''imgWhereAmI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWhereAmI As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RepeaterSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterSteps As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''imgStepsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgStepsList As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblEvaluated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvaluated As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cbAutoAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAutoAdvance As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextUnas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextUnas As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFirst As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrev As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divNextHint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNextHint As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''isFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isFinish As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadToolTipWhereAmI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipWhereAmI As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''divTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTree As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadTreeViewHierarchy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewHierarchy As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''divNoSources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoSources As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadTreeViewNoSources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewNoSources As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''divTreeImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTreeImpact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadTreeViewImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewImpact As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadToolTipStepsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipStepsList As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''divStepsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStepsList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RepStepsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepStepsList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ttJump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttJump As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''btnJump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJump As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadtooltipNavHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadtooltipNavHelp As Global.Telerik.Web.UI.RadToolTip
End Class
