'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FramedInfodDocs

    '''<summary>
    '''speditable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speditable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''parent_tooltip_trigger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parent_tooltip_trigger As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtparentnode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtparentnode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''span2editable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents span2editable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dveditconetnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dveditconetnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvblank1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvblank1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvBlank2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvBlank2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvWindowscontecnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvWindowscontecnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spdesktop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spdesktop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sp_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_magnifyedit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_magnifyedit As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''txtleftnode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtleftnode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dvconetcnt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvconetcnt2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_leftnode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_leftnode As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_hide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_hide As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvinfodoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvinfodoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvParentNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvParentNode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_0 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_infodoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_infodoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sp_p0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_p0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_pnode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_pnode As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''txtpNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpNode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dvinfodoc_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvinfodoc_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ainfodoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ainfodoc As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spicon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spicon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvNoMmbile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvNoMmbile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_icon_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_icon_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sp_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_maginify2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_maginify2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''txtpnode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpnode1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dvcontent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvcontent1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''aNode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aNode1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_icon2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvDocright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvDocright As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvBlank3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvBlank3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvBlank4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvBlank4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvleft3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvleft3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spicon3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spicon3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sp_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''aleftnode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aleftnode As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''dvleftnode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvleftnode1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''anodeleft1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents anodeleft1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_icon3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_icon3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvdocleft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvdocleft As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvnode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvnode3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvnode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvnode4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spicon4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spicon4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sp_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''anodeleft2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents anodeleft2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''dvnode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvnode5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''anode5left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents anode5left As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''sp_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvdocright2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvdocright2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dvBlank5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvBlank5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
