//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnytimeComparion.Pages {
    
    
    public partial class WebForm1 {
        
        /// <summary>
        /// DirectComparison control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.DirectComparison DirectComparison;
        
        /// <summary>
        /// DirectComparisonEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.DirectComparisonEvaluation DirectComparisonEvaluation;
        
        /// <summary>
        /// DirectComparisonPrioritiesEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.DirectComparisonPrioritiesEvaluation DirectComparisonPrioritiesEvaluation;
        
        /// <summary>
        /// DirectComparisonPriorities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.DirectComparisonPriorities DirectComparisonPriorities;
        
        /// <summary>
        /// PairWiseComparison control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.PairWiseComparison PairWiseComparison;
        
        /// <summary>
        /// PairWiseComparisonEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.PairWiseComparisonEvaluation PairWiseComparisonEvaluation;
        
        /// <summary>
        /// AllPairWiseComparison control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.AllPairWiseComparison AllPairWiseComparison;
        
        /// <summary>
        /// RatingScale control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.RatingScale RatingScale;
        
        /// <summary>
        /// RatingScaleEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.RatingScaleEvaluation RatingScaleEvaluation;
        
        /// <summary>
        /// UtilityCurve control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.UtilityCurve UtilityCurve;
        
        /// <summary>
        /// UtilityCurveEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.UtilityCurveEvaluation UtilityCurveEvaluation;
        
        /// <summary>
        /// StepFunction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.StepFunction StepFunction;
        
        /// <summary>
        /// StepFunctionEvaluation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.StepFunctionEvaluation StepFunctionEvaluation;
        
        /// <summary>
        /// Priorities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.Priorities Priorities;
        
        /// <summary>
        /// InformationPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.JudgmentTemplates.InformationPage InformationPage;
        
        /// <summary>
        /// needToLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.NeedToLogin needToLogin;
    }
}
