'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlShowResults2
        
        '''<summary>
        '''imgVertSpacer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgVertSpacer As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''RadSplitterResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadSplitterResults As Global.Telerik.Web.UI.RadSplitter
        
        '''<summary>
        '''radPanelTree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radPanelTree As Global.Telerik.Web.UI.RadPane
        
        '''<summary>
        '''RadTreeViewHierarchy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTreeViewHierarchy As Global.Telerik.Web.UI.RadTreeView
        
        '''<summary>
        '''RadSplitbarLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadSplitbarLeft As Global.Telerik.Web.UI.RadSplitBar
        
        '''<summary>
        '''radPanelGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radPanelGrid As Global.Telerik.Web.UI.RadPane
        
        '''<summary>
        '''RadAjaxPanelResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxPanelResults As Global.Telerik.Web.UI.RadAjaxPanel
        
        '''<summary>
        '''tdNormalizationMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdNormalizationMode As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''ddResultsMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddResultsMode As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''GridResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridResults As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''lblInconsistency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInconsistency As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''AjaxLoadingPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AjaxLoadingPanel As Global.Telerik.Web.UI.RadAjaxLoadingPanel
        
        '''<summary>
        '''LoadingPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoadingPanel As Global.ExpertChoice.Web.Controls.ctrlLoadingPanel
    End Class
End Namespace
