'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlMultiPairwise
        
        '''<summary>
        '''tooltipLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipLegend As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''divLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLegend As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''frmInfodocNodeLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocNodeLeft As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocGoal As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocNodeRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocNodeRight As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocWRTLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRTLeft As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocWRTRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRTRight As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''imgCaptionInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCaptionInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipGoal As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''rptPW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPW As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
