'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlUtilityCurve
        
        '''<summary>
        '''imgCaptionInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCaptionInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipGoal As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''imgAltInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAltInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipAltInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipAltInfodoc As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''imgWRTInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgWRTInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipWRTInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipWRTInfodoc As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''pnlComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlComment As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''frmInfodocGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocGoal As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocNode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocNode As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRT As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocScale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocScale As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlRUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRUC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''imgScaleInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgScaleInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipScaleInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipScaleInfodoc As Global.Telerik.Web.UI.RadToolTip
    End Class
End Namespace
