'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlMultiRatings
        
        '''<summary>
        '''tdInfodocLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdInfodocLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''tdInfodocCenter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdInfodocCenter As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''frmInfodocWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRT As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocScale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocScale As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''trCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCaption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''imgCaptionInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCaptionInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipGoal As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''rptAlts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptAlts As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''tooltipScaleDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipScaleDesc As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''ttEditDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ttEditDescription As Global.Telerik.Web.UI.RadToolTip
    End Class
End Namespace
