'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlMultiDirectInputs
        
        '''<summary>
        '''tdLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''tdCenter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdCenter As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''frmInfodocWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRT As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''imgCaptionInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCaptionInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipGoal As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''rptDI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptDI As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
