'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlPairwiseBar
        
        '''<summary>
        '''imgCaptionInfodoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCaptionInfodoc As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipGoal As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''frmInfodocGoal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocGoal As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''ImageLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageLeft As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipLeft As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblNode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNode1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ImageLeftWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageLeftWRT As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipLeftWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipLeftWRT As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''pnlGPW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGPW As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''ImageRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageRight As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipRight As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''lblNode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNode2 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ImageRightWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageRightWRT As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''tooltipRightWRT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tooltipRightWRT As Global.Telerik.Web.UI.RadToolTip
        
        '''<summary>
        '''phScale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phScale As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''frmInfodocLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocLeft As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocWRTLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRTLeft As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''btnUndefined control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUndefined As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pnlComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlComment As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''frmInfodocRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocRight As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''frmInfodocWRTRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfodocWRTRight As Global.ExpertChoice.Web.Controls.ctrlFramedInfodoc
        
        '''<summary>
        '''mapVerbalPW control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mapVerbalPW As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
