'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ExpertChoice.Web.Controls
    
    Partial Public Class ctrlSensitivityAnalysis
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
