'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RiskResultsPage
    
    '''<summary>
    '''ScriptManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerMain As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptBlock As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadSplitterMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitterMain As Global.Telerik.Web.UI.RadSplitter
    
    '''<summary>
    '''RadPaneHierarchy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPaneHierarchy As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''RadAjaxPanelTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanelTree As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadCodeBlockTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockTree As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''RadTreeHierarchy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeHierarchy As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadSplitRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitRight As Global.Telerik.Web.UI.RadSplitBar
    
    '''<summary>
    '''RadPaneGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPaneGrid As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''divGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadCodeBlockGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockGrid As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''btnEditRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditRegions As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''divHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divFilterData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFilterData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divNodesDataWithDollars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNodesDataWithDollars As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridResults As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivRiskMapData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivRiskMapData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnResetZoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetZoom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivBowTieData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivBowTieData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivGridColorLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivGridColorLegend As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadNumericTextBoxRh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxRh As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''RadNumericTextBoxRl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxRl As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''RadTreeViewLikelihood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewLikelihood As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadTreeViewImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewImpact As Global.Telerik.Web.UI.RadTreeView
End Class
