<h5>How to evaluate using Single Pairwise Graphical/Numerical:</h5>

<p>You can enter a judgment by clicking or dragging the slider bar or by entering a number in the left or right boxes below the slider bar. You can drag the bar only up to ratio 9:1 as the extreme. Judgments with ratios > 9 to 1 can be entered numerically which will move the slider on the extra white spaces from 9.<p/>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d6cce21ad121ce06aa48062/n/single-pw-graphical.gif" alt="single pairwise graphical" width="100%" height="auto">
