<h5>How to evaluate using Single Pairwise Verbal:</h5>

<p>You can enter a judgment by clicking on the bar that expresses your judgment about the relative importance of one objective over the other objective. You can also select an intensity between any of the words, such as between Moderately and Strong.<p/>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d639559ec161c3d166f95c4/n/single-pw-verbal.gif" alt="single pairwise verbal" width="100%" height="auto">



