'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Spyron_Surveys_ctrlSurveyQuestion
    
    '''<summary>
    '''tblQuestionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblQuestionForm As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''trQuestionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestionForm As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''tcQuestionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcQuestionForm As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''erEmptyFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents erEmptyFields As Global.System.Web.UI.WebControls.Label
End Class
