'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Anytime
    
    '''<summary>
    '''hdnPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageNumber As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnCurrentStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCurrentStep As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnTotalSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTotalSteps As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnparentnodeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnparentnodeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''intermediate_screen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents intermediate_screen As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''InformationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InformationControl As Global.AnytimeComparion.InformationUserCtrl
    
    '''<summary>
    '''AllPairWiseControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllPairWiseControl As Global.AnytimeComparion.AllPairWiseUserCtrl
    
    '''<summary>
    '''SurveyControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyControl As Global.AnytimeComparion.Survey
    
    '''<summary>
    '''LocalResultsControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalResultsControl As Global.AnytimeComparion.localresults
    
    '''<summary>
    '''footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents footer1 As Global.AnytimeComparion.Footer
End Class
