'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomResultsPage
    
    '''<summary>
    '''ScriptManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerMain As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''pnlReportOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReportOptions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGroups As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ASPxPageControlReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControlReports As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl
    
    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.XtraPivotGrid.Web.ASPxPivotGridExporter
    
    '''<summary>
    '''Panel0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel0 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport0 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnGeneratePrioritesOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGeneratePrioritesOverview As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnRTF0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF0 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF0 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS0 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''chkAllUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllUsers As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
    
    '''<summary>
    '''_AltName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _AltName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''_UserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _UserName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''_AltGlobalPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _AltGlobalPriority As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnGeneratePWJudgements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGeneratePWJudgements As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnRTF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''ASPxGridViewExporter3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter3 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport3 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnObjPriorities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnObjPriorities As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnRTF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF3 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF3 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS3 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView3 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''ASPxGridViewExporter4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter4 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport4 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnEvalProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEvalProgress As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnRTF4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF4 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF4 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS4 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView4 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''ContentControl5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl5 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''ASPxGridViewExporter5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter5 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''Panel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport5 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnInconsistency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInconsistency As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnRTF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF5 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF5 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS5 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView5 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''ContentControl6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl6 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''dsRespondentAnswers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRespondentAnswers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsStatisticResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsStatisticResults As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsRespondentAnswers2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRespondentAnswers2 As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsStatisticResults2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsStatisticResults2 As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''lblNoWelcomeSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoWelcomeSurvey As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelWelcomeSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWelcomeSurvey As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSurveyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSurveyTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWSurveyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWSurveyTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport6 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnRTF6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF6 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF6 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS6 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridViewExporterResultOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporterResultOverview As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''gvResultOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvResultOverview As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''Panel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel7 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport7 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnRTF7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF7 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF7 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS7 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridViewExporterStatisticResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporterStatisticResults As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''gvStatisticResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStatisticResults As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''lblNoThankyouSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoThankyouSurvey As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelThankyouSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelThankyouSurvey As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTSurveyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTSurveyTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel8 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport8 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnRTF8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF8 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF8 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS8 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridViewExporterResultOverview2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporterResultOverview2 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''gvResultOverview2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvResultOverview2 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''Panel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel9 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbExport9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbExport9 As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''btnRTF9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRTF9 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnPDF9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF9 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''btnXLS9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXLS9 As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''ASPxGridViewExporterStatisticResults2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporterStatisticResults2 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
    
    '''<summary>
    '''gvStatisticResults2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStatisticResults2 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''ContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl3 As Global.DevExpress.Web.ASPxClasses.ContentControl
End Class
