'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportView
    
    '''<summary>
    '''ASPxPageControlReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControlReports As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl
    
    '''<summary>
    '''CtrlReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport1 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''cbFullPath2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFullPath2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDescription2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport2 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport8 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''cbFullPath3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFullPath3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport3 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''CtrlReport4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport4 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''CtrlReport10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport10 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''cbFullPath5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFullPath5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbBars1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBars1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport5 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''cbBars2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBars2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport6 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''cbFullPath6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFullPath6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbLocal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLocal6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbGlobal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbGlobal6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CtrlReport7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport7 As Global.ExpertChoice.Web.Controls.ctrlReport
    
    '''<summary>
    '''CtrlReport9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlReport9 As Global.ExpertChoice.Web.Controls.ctrlReport
End Class
