<h5>How to evaluate using Multi-rating:</h5>

<p>The fastest way to enter a rating is to click on an intensity name, such as "Moderate to Good" at the right side of the page. After clicking the intensity name, the highlight advances to the next alternative. The priority corresponding to the verbal intensities are shown also at the right of the page. </p>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d6cdf5b8e121ca0122f19ba/n/multi-rating.gif" alt="ratings" width="100%" height="auto">
