<h5>How to evaluate using Multi-graphical/numerical:</h5>

<p>You can drag the bar only up to ratio 9:1 as the extreme (see Performance vs. Style). Judgments with ratios > 9 to 1 can be entered numerically which will move the slider on the extra white spaces from 9. </p>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d6cd3b1ad121c9177a47fb0/n/multi-pw-gn.gif" alt="mutli-pw graphical numerical" width="100%" height="auto">
