'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AllPairWiseUserCtrl

    '''<summary>
    '''question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents question As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''QuestionHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionHeader As Global.QuestionHeader

    '''<summary>
    '''FramedInfodDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FramedInfodDocs As Global.FramedInfodDocs

    '''<summary>
    '''dvContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GlobalInfoIconsModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GlobalInfoIconsModal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''saveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents saveStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
