'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctUtilityCurve

    '''<summary>
    '''hdnXMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnXMin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnXMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnXMax As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDecreasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDecreasing As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnCurvature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCurvature As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnXValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnXValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divutc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divutc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HeaderInfoRigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderInfoRigh As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''faqlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents faqlist As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UtDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UtDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''infoScale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoScale As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClose As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''infoScale1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoScale1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgCloseOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCloseOne As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''infoDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ditest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ditest As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
