'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''bootstrapstyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bootstrapstyle As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''appstyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents appstyle As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''InviteTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InviteTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''SPass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPass2 As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''modalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''msgPasswordRestore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgPasswordRestore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ResetEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetEmail As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
