'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WorkgroupTemplatesPages
    
    '''<summary>
    '''MainModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainModal As Global.ExpertChoice.Web.Controls.ctrlModalProcess
    
    '''<summary>
    '''ASPxRoundPanelLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanelLoading As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel
    
    '''<summary>
    '''ASPxCallbackPasscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallbackPasscode As Global.DevExpress.Web.ASPxCallback.ASPxCallback
    
    '''<summary>
    '''ASPxPageControlSources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControlSources As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl
    
    '''<summary>
    '''ContentControlFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControlFiles As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''lblFilesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilesList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ContentControlStartup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControlStartup As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''lblStartup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ASPxPageControlDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControlDest As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl
    
    '''<summary>
    '''ContentControlExists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControlExists As Global.DevExpress.Web.ASPxClasses.ContentControl
    
    '''<summary>
    '''lblExisted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExisted As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
