//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnytimeComparion.Pages.JudgmentTemplates {
    
    
    public partial class DirectUser {
        
        /// <summary>
        /// QuestionHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.QuestionHeader QuestionHeader;
        
        /// <summary>
        /// LeftNodeInfoDoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.LeftNodeInfoDoc LeftNodeInfoDoc;
        
        /// <summary>
        /// ParentNodeInfoDoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.ParentNodeInfoDoc ParentNodeInfoDoc;
        
        /// <summary>
        /// WRTLeftNodeInfoDoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.WRTLeftNodeInfoDoc WRTLeftNodeInfoDoc;
    }
}
