//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnytimeComparion.Pages {
    
    
    public partial class Participants {
        
        /// <summary>
        /// SidebarRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.sidebar SidebarRight;
        
        /// <summary>
        /// needToLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnytimeComparion.Pages.includes.NeedToLogin needToLogin;
    }
}
