<h5>How to evaluate using Multi-pairwise verbal:</h5>

<p>For each pair, you can enter a judgment by clicking on the bar that expresses your judgment. You select equal, or specify an intensity on either side of equal. The intensities can moderate, strong, very strong or extreme, be between any of the words, such as between moderately and strongly. </p>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d639c468e121c682cb1f0f6/n/multi-pw-verbal.gif" alt="mutli-pw verbal" width="100%" height="auto">
