<h5>How to evaluate using Step Function:</h5>

<p>The data can be entered by dragging the handle of the vertical slider or typing on the textbox provided, the corresponding priority will be shown in the graph. From our example, the data entered is 40 and the resulting priority is 40%. </p>

<img src="https://dyzz9obi78pm5.cloudfront.net/app/image/id/5d6e14c0ec161c050c6d7152/n/step-function-pl.gif" alt="step function" width="100%" height="auto">
