'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RABasePage
    
    '''<summary>
    '''ScriptManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerMain As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptBlock As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadAjaxManagerMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerMain As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadToolBarMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarMain As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''divGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGrid As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''pnlIgnore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIgnore As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tooltipTPIgnored control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tooltipTPIgnored As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''pnlBaseCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBaseCase As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridAlternatives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridAlternatives As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hfGridView1SV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridView1SV As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfGridView1SH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridView1SH As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LinkedCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkedCC As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''SolverActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SolverActive As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''radCodeBlockDlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCodeBlockDlg As Global.Telerik.Web.UI.RadCodeBlock
End Class
