'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RATimelinePage
    
    '''<summary>
    '''btnExpandProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExpandProjects As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''btnContractProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContractProjects As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''btnTrimTimeline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTrimTimeline As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
