'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class my_projects
    
    '''<summary>
    '''hdnButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnSortingReverse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSortingReverse As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnisAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnisAdmin As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnProjectsLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnProjectsLength As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnPageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnPairwiseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPairwiseType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnwkgRoleGroupId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnwkgRoleGroupId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''select_workgroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_workgroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pageCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageCount As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''pageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageOptions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''select_workgroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_workgroup2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rptdataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptdataGrid As Global.System.Web.UI.WebControls.Repeater
End Class
