'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TeamTimeEvaluationPage
    
    '''<summary>
    '''RadtooltipHotkeys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadtooltipHotkeys As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''imgNavHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNavHelp As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ASPxCallbackTeamTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallbackTeamTime As Global.DevExpress.Web.ASPxCallback.ASPxCallback
    
    '''<summary>
    '''pnlLoadingNextStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoadingNextStep As Global.ExpertChoice.Web.Controls.ctrlLoadingPanel
    
    '''<summary>
    '''ttJump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttJump As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''ttSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttSettings As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''RadToolTipWhereAmI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipWhereAmI As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''divTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTree As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadTreeViewHierarchy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewHierarchy As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadToolTipStepsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipStepsList As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''RadToolTipEvaluationProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipEvaluationProgress As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''RadToolTipInfodoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipInfodoc As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''ResizableControlExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResizableControlExtender As Global.AjaxControlToolkit.ResizableControlExtender
    
    '''<summary>
    '''lblInfodocPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfodocPanel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadtooltipNavHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadtooltipNavHelp As Global.Telerik.Web.UI.RadToolTip
End Class
