'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectTeamTimeStatusPage
    
    '''<summary>
    '''brdOptionsWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents brdOptionsWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''brdRolesWarningTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents brdRolesWarningTag As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''brdRolesWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents brdRolesWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
