Imports ExpertChoice.Data

Public Class FramedInfodDocs
    Inherits System.Web.UI.UserControl

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

    End Sub
    Public Sub BindHtml(ByRef output As AnytimeOutputModel)
        Dim active_multi_index = 1
        Dim isOwner As Double = 0
        Dim is_screen_reduced = False
        Dim isMobile = False
        Dim App = CType(Session("App"), clsComparionCore)
        If output.owner = App.ActiveUser.UserName.ToString() Then
            isOwner = 1
        End If
        Dim collapsed_info_docs = output.multi_collapse_default
        Dim html As StringBuilder = New StringBuilder()
        html.Append(active_multi_index)
        If output.multi_GUIDs IsNot Nothing Then
            html.Append($"<br />" + output.multi_GUIDs(active_multi_index)(1))
            html.Append(output.multi_GUIDs(active_multi_index)(2))
        End If
        If output.multi_infodoc_params IsNot Nothing Then
            html.Append(output.multi_infodoc_params(active_multi_index))
        End If
        html.Append("<div style='margin-bottom:5px;' class='InfoDocsParentDiv'>")
        If output.is_infodoc_tooltip And output.showinfodocnode Then
            html.Append("<span class='" + If((String.IsNullOrWhiteSpace(output.parent_node_info) And isOwner = 0), "hide", "") + "'>")
            html.Append(" <div class='row editable-content'>  <div class='large-4 columns large-centered'>  <div class='text-center'>")
            html.Append(" <a data-dropdown='gdrop0' data-options='is_hover:true; hover_timeout:1000' aria-controls='gdrop0' aria-expanded='false' data-node-type='-1' data-location='-1' data-node='parent-node' ")
            html.Append($"data-node-description='" + output.parent_node + "' data-readonly='" + If(isOwner = 0, 1, 0) + "'")
            html.Append($" class='parent-node-tooltip tooltip-infodoc-btn' id='parent_tooltip_trigger'> <span class='" + If(String.IsNullOrWhiteSpace(output.parent_node_info), "disabled", "") + "'  style='font-size:  14px;' class='icon icon-tt-info-circle small'></span></a>")
            html.Append($"<span id='0' class='text parent-lbl parent-node hide-When-editing-0 text editable-trigger143 et-0 small'> " + output.parent_node + "    </span></div>")
            html.Append("<div class='row collapse editable-input-wrap eiw-0'> <div class='small-12 columns'>")
            html.Append("<input value='" + output.parent_node + "' name='' placeholder='Add something here' type='text' class='text editable-input ei-0' />")
            html.Append("</div> <div class='small-12 columns'> <a id='0' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append(" <a  id='0' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div></div></div></span>")
        End If
        If (Not output.is_infodoc_tooltip Or (isOwner = 0 And output.framed_info_docs)) And (output.page_type = "atAllPairwise" Or output.page_type = "atAllPairwiseOutcomes") And output.showinfodocnode Then
            html.Append($"<span>  <div class='row editable-content" + If((isMobile And output.framed_info_docs), "editable-content-height", "") + "'>")
            If String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0 Then
                html.Append("<div class='columns large-3 hide-for-medium-down'> &nbsp; </div>")
            End If
            If isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info) Then
                html.Append(" <div class='columns large-2 hide-for-medium-down'>&nbsp;</div>")
            End If
            If Not isMobile Then
                html.Append($"<div class='" + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-3", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-4", "") + " columns'>")
                html.Append($" <div class='text-center'> <a class='" + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)))), "tt-toggler", "") + " tt-toggler-1'  id='1'  data-toggler='tg-accordion-Sub'>  <span class='" + If(((output.showinfodocnode) And Not collapsed_info_docs(1)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(1)), "icon-tt-plus-square", "") + " icon icon-desktop' data-node='1'></span> </a>")
                html.Append($" <span id='1' class='left-node hide-when-editing-1 text editable-trigger143 et-1 small' style='font-size:    12px;'> " + If(output.hideInfoDocCaptions, "", If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode)) + "   </span>")
                If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) Then
                    html.Append("<a class='magnify-icon edit-info-doc-btn'  data-index='" + active_multi_index.ToString() + "' data-node-type='2' data-location='1' data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Left) + "' ")
                    html.Append(" data-node='left-node' data-node-description='" + output.multi_pw_data(active_multi_index).LeftNode + "' data-readonly='1'>")
                    html.Append(" <span class='icon icon-tt-zoom-in'></span> </a> </div>")
                End If
            End If
            html.Append(" <div class='row collapse editable-input-wrap eiw-1'><div class='small-12 columns'>")
            html.Append("<input value='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-1' />")
            html.Append("</div> <div class='small-12 columns'><a id='1' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a> <a  id='1' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a> </div> </div>")
            html.Append("<div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(1) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0)), "hide", "") + " left-node-info-div tt-accordion-content tg-accordion-1  tg-accordion-sub-1'>")
            html.Append("<div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-1' data-box-index='1' style='max-height: 90px;'>")
            html.Append("<a data-index='" + active_multi_index.ToString() + "'  class='edit-info-doc-btn edit-pencil ep ep-sub-1 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(1)), "hide", "") + "' data-node-type='2' data-location='1' data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Left) + "' data-node='left-node'  data-node-description='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "' title='' href='#'> ")
            html.Append(" <span class='icon-tt-pencil" + If(isOwner <> 1, "hide", "") + "'></span> </a>")
            html.Append("<div  class='left-node-info-text" + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft) + " </div> </div> </div> </div>")
        End If
        html.Append($" <div class='columns original-info-doc " + If(((String.IsNullOrWhiteSpace(output.parent_node_info) And isOwner = 0)), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-6", "") = " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-2", "") + "'>")
        html.Append($" <div class='text-center'><a class='tt-toggler-0 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "tt-toggler", "") + "' id='0' data-toggler='tg-accordion' onclick='set_collapse_cookies('parent-node'); update_infodoc_params('parent-node', output.ParentNodeGUID, '')'><span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(0)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(0)), "icon-tt-plus-square", "") + "' data-node='0'></span> </a>")
        html.Append($" <span id='0' class='text parent-lbl parent-node hide-when-editing-0 text editable-trigger143 et-0 small' style='font-size: 12px;'> " + If(output.hideInfoDocCaptions, "", output.parent_node) + "</span>  ")
        If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info) Then
            html.Append("<a class='magnify-icon edit-info-doc-btn'  data-index='" + active_multi_index.ToString() + "' data-node-type='-1' data-location='-1' data-node='parent-node' data-node-description='" + output.parent_node + "' data-readonly='1'><span class='icon icon-tt-zoom-in'></span> </a>")
        End If
        html.Append(" </div>")
        html.Append(" <div class='row collapse editable-input-wrap eiw-0'> <div class='small-12 columns'> <input value='" + output.parent_node + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-0' />")
        html.Append("</div><div class='small-12 columns'><a id='0' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
        html.Append("<a   id='0' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a> </div> </div>")
        html.Append($" <div class='parent-node-info-div  tt-accordion-content tg-accordion-0  tg-accordion-sub-0 " + If((Not output.showinfodocnode Or collapsed_info_docs(0) Or (String.IsNullOrWhiteSpace(output.parent_node_info) And isOwner = 0)), "hide", "") + "'> ")
        html.Append("<div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-0 tt-resizable-panel-1 small-centered columns box-0' data-box-index='0'> <a  data-index='" + active_multi_index.ToString() + "'  data-node-type='-1' data-location='-1' data-node='parent-node' data-node-description='" + output.parent_node + "' class='edit-info-doc-btn edit-pencil ep ep-0 ep-sub-0 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(0)), "hide", "") + "'  title=''  href='#'>")
        html.Append("<span class='icon-tt-pencil " + If(isOwner <> 1, "hide", "") + "></span></a>")
        html.Append($"<div class='parent-node-info-text" + If(is_screen_reduced, "zoom-out", "") + "'>" + output.parent_node_info + " </div> </div> </div> </div>")
        If Not isMobile Then
            html.Append(" <div  class='columns " + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-3", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-4", "") + "'> <div class='text-center'>")
            html.Append("<a onclick='set_collapse_cookies('right-node'); update_infodoc_params('right-node', output.ParentNodeGUID, '')' class='tt-toggler-2 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)))), "tt-toggler", "") + "' id='2' data-toggler='tg-accordion-sub'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(2)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(2)), "icon-tt-plus-square", "") + "' data-node='2' ></span> </a>")
            html.Append(" <span id='2' class='right-node hide-when-editing-2 text editable-trigger143 et-2 small' style='font-size: 12px;'>  " + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "   </span>")
            If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) Then
                html.Append("<a class='magnify-icon edit-info-doc-btn' data-node-description='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "' data-location='2' data-node='right-node' data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "' data-readonly='1'> ")
                html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
            End If
            html.Append(" </div>")
        End If
        html.Append(" <div class='row collapse editable-input-wrap eiw-2'> <div class='small-12 columns'><input value = '" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-2' /></div> <div class='small-12 columns'><a id='2' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
        html.Append("<a   id='2' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
        html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(2) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) And isOwner = 0)), "hide", "") + " right-node-info-div  tt-accordion-content tg-accordion-2  tg-accordion-sub-2'>")
        html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-2' data-box-index='2' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='2'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-2 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(2)), "hide", "") + "' data-node='right-node'  data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Right) + "'  data-node-description='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  title='' href='#'> <span  class='icon-tt-pencil" + If(isOwner <> 1, "hide", "") + "'></span>   ")
        html.Append("</a>   <div  class='right-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight) + "  </div> </div> </div> </div>")
        If isMobile And output.framed_info_docs Then
            html.Append("<div class='row editable-content mobile-frame'>")
            If isOwner = 0 And String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) Then
                html.Append("<div class='columns small-6'>  &nbsp; </div>")
            End If
            html.Append("<div class='columns small-6" + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0), "hide", "") + "'>")
            html.Append("<div class='text-center'><a  class=' tt-toggler-1 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)))), "tt-toggler", "") + "' onclick='set_collapse_cookies('left-node'); update_infodoc_params('left-node', output.ParentNodeGUID, '')  id='1'  data-toggler='tg-accordion-sub'> <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(1)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(1)), "icon-tt-plus-square", "") + "' data-node='1'></span> </a>")
            html.Append(" <span id='1' class='left-node hide-when-editing-1 text editable-trigger143 et-1 small' style='font-size:  12px;'> " + If(output.hideInfoDocCaptions, "", output.multi_pw_data(active_multi_index).LeftNode) + "    </span></div>")
            html.Append(" <div class='row collapse editable-input-wrap eiw-1'> <div class='small-12 columns'><input value = '" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-1' /></div> <div class='small-12 columns'><a id='1' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append("<a   id='1' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
            html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(1) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0)), "hide", "") + " left-node-info-div tt-accordion-content tg-accordion-1  tg-accordion-sub-1'>")
            html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-1' data-box-index='1' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='2'  data-location='1' class='edit-info-doc-btn edit-pencil ep ep-sub-1 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(2)), "hide", "") + "' data-node='left-node'  data-node-id='" + output.multi_pw_data(active_multi_index).NodeID_Left + "'  data-node-description='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
            html.Append("</a>   <div  class='left-node-info-text" + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft) + "  </div> </div> </div> </div>")
            html.Append("<div class='columns small-6" + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) And isOwner = 0), "hide", "") + "'>")
            html.Append("<div class='text-center'><a  class=' tt-toggler-2 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)))), "tt-toggler", "") + "' onclick='set_collapse_cookies('right-node'); update_infodoc_params('right-node', output.ParentNodeGUID, '')  id='1'  data-toggler='tg-accordion-sub'> <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(1)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(1)), "icon-tt-plus-square", "") + "' data-node='2'></span> </a>")
            html.Append(" <span id='2' class='right-node hide-when-editing-2 text editable-trigger143 et-2 small' style='font-size:  12px;'> " + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "    </span></div>")
            html.Append(" <div class='row collapse editable-input-wrap eiw-2'> <div class='small-12 columns'><input value = '" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-2' /></div> <div class='small-12 columns'><a id='2' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append("<a   id='2' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
            html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(2) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) And isOwner = 0)), "hide", "") + " right-node-info-div  tt-accordion-content tg-accordion-2  tg-accordion-sub-2'>")
            html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-2' data-box-index='2' style='max-height: 90px;'><a data-index='" + active_multi_index + "' data-node-type='2'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-2 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(2)), "hide", "") + "' data-node='right-node'  data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Right) + "'  data-node-description='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
            html.Append("</a>   <div  class='right-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight) + "  </div> </div> </div> </div>")
            If isOwner = 0 And String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) Then
                html.Append("<div  class='columns small-6'> &nbsp;</div>")
            End If
            html.Append("</div>")
        End If
        If isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info) Then
            html.Append("<div  class='columns large-2 hide-for-medium-down'>&nbsp;</div>")
        End If
        html.Append("</div>")
        html.Append(" <div class='row editable-content'>")
        If isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info) Then
            html.Append("<div  class='columns large-2 hide-for-medium-down'>&nbsp;</div>")
        End If
        html.Append(" <div  class='columns " + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeftWRT)) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-3", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-4", "") + "'> <div class='text-center'>")
        html.Append("<a onclick='set_collapse_cookies('wrt-left-node'); update_infodoc_params('wrt-left-node', output.ParentNodeGUID, '')' class='tt-toggler-3 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeftWRT)))), "tt-toggler", "") + "' id='3' data-toggler='tg-accordion-sub'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(2)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(2)), "icon-tt-plus-square", "") + "' data-node='3' ></span> </a>")
        html.Append(" <span id='3' class='right-node hide-when-editing-3 text editable-trigger143 et-3 small' style='font-size: 12px;'>  " + If(output.hideInfoDocCaptions, "", "get_wrt_text('left')") + "   </span>")
        If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeftWRT)) Then
            html.Append("<a class='magnify-icon edit-info-doc-btn' data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Left) + "' data-node-description='" + output.parent_node + "' data-location='3' data-node='left-node' data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "' data-readonly='1'> ")
            html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
        End If
        html.Append(" </div>")
        html.Append(" <div class='row collapse editable-input-wrap eiw-3'> <div class='small-12 columns'><input value = '" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-3' /></div> <div class='small-12 columns'><a id='3' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
        html.Append("<a   id='3' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
        html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(3) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeft)) And isOwner = 0)), "hide", "") + " left-node-info-div  tt-accordion-content tg-accordion-3  tg-accordion-sub-3'>")
        html.Append(" <div data-index='3' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-2 small-centered columns box-3' data-box-index='3' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='3'  data-location='1' class='edit-info-doc-btn edit-pencil ep ep-sub-3 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(2)), "hide", "") + "' data-node='left-node'  data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Left) + "'  data-node-description='" + output.parent_node + "'  data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).LeftNode) + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
        html.Append("</a>   <div  class='wrt-left-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeftWRT) + "  </div> </div> </div> </div>")
        html.Append("<div  class='columns " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-6", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-2", "") + "'>")
        html.Append(" <div  class='tt-accordion-content tg-accordion-0  tg-accordion-sub-0'></div></div>")
        html.Append(" <div  class='columns " + If((String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRightWRT)) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-3", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-4", "") + "'> <div class='text-center'>")
        html.Append("<a onclick='set_collapse_cookies('wrt-right-node'); update_infodoc_params('wrt-right-node', output.ParentNodeGUID, '')' class='tt-toggler-4 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocLeftWRT)))), "tt-toggler", "") + "' id='4' data-toggler='tg-accordion-sub'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(4)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(4)), "icon-tt-plus-square", "") + "' data-node='4' ></span> </a>")
        html.Append(" <span id='4' class='wrt-node hide-when-editing-4 text editable-trigger143 et-4 small' style='font-size: 12px;'>  " + If(output.hideInfoDocCaptions, "", "get_wrt_text('right')") + "   </span>")
        If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRightWRT)) Then
            html.Append("<a class='magnify-icon edit-info-doc-btn' data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Right) + "' data-node-description='" + output.parent_node + "' data-location='3' data-node='left-node' data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "' data-readonly='1'> ")
            html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
        End If
        html.Append(" </div>")
        html.Append(" <div class='row collapse editable-input-wrap eiw-4'> <div class='small-12 columns'><input value = '" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-4' /></div> <div class='small-12 columns'><a id='4' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
        html.Append("<a   id='4' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
        html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(4) Or (String.IsNullOrWhiteSpace(If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRight)) And isOwner = 0)), "hide", "") + " right-node-info-div  tt-accordion-content tg-accordion-4  tg-accordion-sub-4'>")
        html.Append(" <div data-index='4' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-3 small-centered columns box-4' data-box-index='4' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='3'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-4 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(4)), "hide", "") + "' data-node='right-node'  data-node-id='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).NodeID_Right) + "'  data-node-description='" + output.parent_node + "'  data-node-title='" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).RightNode) + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
        html.Append("</a>   <div  class='wrt-right-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + If(output.multi_pw_data Is Nothing, "", output.multi_pw_data(active_multi_index).InfodocRightWRT) + "  </div> </div> </div> </div>")
        If isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info) Then
            html.Append("<div  class='columns large-2 hide-for-medium-down'>&nbsp;</div>")
        End If
        html.Append("</div></span>")
        If Not output.is_infodoc_tooltip And (output.page_type = "atNonPWAllChildren" Or output.page_type = "atNonPWAllCovObjs") And output.showinfodocnode Then
            html.Append("<span > <div class='row editable-content'>")
            If String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc) And isOwner = 0 Then
                html.Append("<div  class='columns large-4'>&nbsp;</div>")
            End If
            html.Append(" <div  class='columns hide-for-medium-down" + If((String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-4", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-6", "") + "'> <div class='text-center'>")
            html.Append("<a onclick='set_collapse_cookies('wrt-right-node'); update_infodoc_params('wrt-right-node', output.ParentNodeGUID, '')' class='tt-toggler-1 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc))), "tt-toggler", "") + "' id='1' data-toggler='tg-accordion-sub'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(1)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(1)), "icon-tt-plus-square", "") + If((isOwner = 0 And (String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc) And isOwner = 0)), "hide", "") + "' data-node='4' ></span> </a>")
            html.Append(" <span id='1' class='left-node hide-when-editing-1 text editable-trigger143 et-1 small' style='font-size: 12px;'>  " + If(output.hideInfoDocCaptions, "", output.multi_non_pw_data(active_multi_index).Title) + "   </span>")
            If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc) Then
                html.Append("<a class='magnify-icon edit-info-doc-btn' data-node-id='" + output.multi_non_pw_data(active_multi_index).ID + "' data-node-description='" + output.multi_non_pw_data(active_multi_index).Title + "' data-location='3' data-node='left-node' data-node-guid='" + output.multi_non_pw_data(active_multi_index).sGUID + "' data-readonly='1'> ")
                html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
            End If
            html.Append("</div>")
            html.Append(" <div class='row collapse editable-input-wrap eiw-1'> <div class='small-12 columns'><input value = '" + output.multi_non_pw_data(active_multi_index).Title + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-1' /></div> <div class='small-12 columns'><a id='1' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append("<a   id='1' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
            html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(1) Or (String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).Infodoc) And isOwner = 0)), "hide", "") + " left-node-info-div tt-accordion-content tg-accordion-1  tg-accordion-sub-1'>")
            html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-1' data-box-index='1' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='3'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-1 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(1)), "hide", "") + "' data-node='left-node'  data-node-id='" + output.multi_non_pw_data(active_multi_index).ID + "'  data-node-description='" + output.multi_non_pw_data(active_multi_index).Title + "'  data-node-guid='" + output.multi_non_pw_data(active_multi_index).sGUID + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
            html.Append("</a>   <div  class='wrt-right-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + output.multi_non_pw_data(active_multi_index).Infodoc + "  </div> </div> </div> </div>")
            html.Append(" <div  class='columns original-info-doc " + If((String.IsNullOrWhiteSpace(output.parent_node_info) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-4", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-6", "") + "'> <div class='text-center'>")
            html.Append("<a onclick='set_collapse_cookies('parent-node'); update_infodoc_params('parent-node', output.ParentNodeGUID, '')' class='tt-toggler-0 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.multi_pw_data(active_multi_index).InfodocLeftWRT))), "tt-toggler", "") + "' id='4' data-toggler='tg-accordion'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(0)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(0)), "icon-tt-plus-square", "") + "' data-node='0' ></span> </a>")
            html.Append(" <span id='0' class='wrt-node hide-when-editing-0 text editable-trigger143 et-0 small' style='font-size: 12px;'>  " + If(output.hideInfoDocCaptions, "", output.parent_node) + "   </span>")
            If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info) Then
                html.Append("<a class='magnify-icon edit-info-doc-btn' data-node-guid='" + output.ParentNodeGUID.ToString() + "' data-node-description='" + output.parent_node + "' data-location='-1' data-node='parent-node' data-node-guid='" + output.multi_non_pw_data(active_multi_index).sGUID + "' data-readonly='1'> ")
                html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
            End If
            html.Append("</div>")
            html.Append(" <div class='row collapse editable-input-wrap eiw-0'> <div class='small-12 columns'><input value = '" + output.multi_non_pw_data(active_multi_index).Title + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-0' /></div> <div class='small-12 columns'><a id='0' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append("<a   id='-' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
            html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(0) Or (String.IsNullOrWhiteSpace(output.parent_node_info) And isOwner = 0)), "hide", "") + " parent-node-info-div  tt-accordion-content tg-accordion-0  tg-accordion-sub-0'>")
            html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-0 tt-resizable-panel-1 small-centered columns box-2' data-box-index='-1'  data-location='-1' data-node-type='-1'  style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='3'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-0 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(0)), "hide", "") + "' data-node='parent-node'  data-node-guid='" + output.ParentNodeGUID.ToString() + "'  data-node-description='" + output.parent_node + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
            html.Append("</a>   <div  class='parent-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + output.parent_node_info + "  </div> </div> </div> </div>")
            html.Append(" <div  class='columns hide-for-medium-down " + If((String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT) And isOwner = 0), "hide", "") + " " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.parent_node_info))), "large-4", "") + " " + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.parent_node_info)), "large-6", "") + "'> <div class='text-center'>")
            html.Append("<a onclick='set_collapse_cookies('wrt-left-node'); update_infodoc_params('wrt-left-node', output.ParentNodeGUID, '')' class='tt-toggler-2 " + If((isOwner = 1 Or (isOwner = 0 And Not String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT))), "tt-toggler", "") + "' id='2' data-toggler='tg-accordion-sub'>  <span class='icon icon-desktop " + If(((output.showinfodocnode) And Not collapsed_info_docs(2)), "icon-tt-minus-square", "") + " " + If((Not output.showinfodocnode Or collapsed_info_docs(2)), "icon-tt-plus-square", "") + If((isOwner = 0 And String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT)), "hide", "") + "' data-node='2' ></span> </a>")
            html.Append(" <span id='2' class='wrt-left-node hide-when-editing-2 text editable-trigger143 et-2 small' style='font-size: 12px;'>  " + If(output.hideInfoDocCaptions, "", "get_wrt_text('right')") + "   </span>")
            If Not (isMobile Or output.is_infodoc_tooltip) And isOwner = 0 And Not String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT) Then
                html.Append("<a class='magnify-icon edit-info-doc-btn' data-index='" + active_multi_index.ToString() + " data-node-id='" + output.multi_non_pw_data(active_multi_index).ID + "' data-node-description='" + output.parent_node + "' data-node-title='" + output.multi_non_pw_data(active_multi_index).Title + " data-location='1' data-node-type='3'  data-node='parent-node' data-node-guid='" + output.multi_non_pw_data(active_multi_index).sGUID + "' data-readonly='1'> ")
                html.Append(" <span class='icon icon-tt-zoom-in'></span></a>")
            End If
            html.Append("</div>")
            html.Append(" <div class='row collapse editable-input-wrap eiw-2'> <div class='small-12 columns'><input value = '" + output.multi_non_pw_data(active_multi_index).Title + "'  name='' placeholder='Add something here' type='text' class='text editable-input ei-2' /></div> <div class='small-12 columns'><a id='2' href='#' class='button tiny tt-button-primary cancel-wrt-btn '>Cancel</a>")
            html.Append("<a   id='2' href='#'  class='button tiny tt-button-primary save-wrt-btn'>Save</a></div></div>")
            html.Append(" <div class='" + If((Not output.showinfodocnode Or collapsed_info_docs(2) Or (String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT) And isOwner = 0)), "hide", "") + " left-node-info-div tt-accordion-content tg-accordion-2  tg-accordion-sub-2'>")
            html.Append(" <div data-index='1' class='tt-panel-temp tt-panel tt-resizable-panel tt-resizable-panel-1 small-centered columns box-3' data-box-index='3' style='max-height: 90px;'><a data-index='" + active_multi_index.ToString() + "' data-node-type='2'  data-location='2' class='edit-info-doc-btn edit-pencil ep ep-sub-2 " + If((isOwner <> 1 Or Not output.showinfodocnode Or collapsed_info_docs(2) Or (String.IsNullOrWhiteSpace(output.multi_non_pw_data(active_multi_index).InfodocWRT) And isOwner = 0)), "hide", "") + "' data-node='wrt-left-node'  data-node-id='" + output.multi_non_pw_data(active_multi_index).ID + "'  data-node-title='" + output.multi_non_pw_data(active_multi_index).Title + "' data-node-description='" + output.parent_node + " data-node-guid='" + output.multi_non_pw_data(active_multi_index).sGUID + "'  title='' href='#'> <span  class='icon-tt-pencil" + If((isOwner <> 1), "hide", "") + "'></span>   ")
            html.Append("</a>   <div  class='wrt-right-node-info-text " + If(is_screen_reduced, "zoom-out", "") + "'>" + output.multi_non_pw_data(active_multi_index).InfodocWRT + "  </div> </div> </div> </div></div>")
            html.Append("</span>")
        End If
        html.Append("</div>")
        dvContent.InnerHtml = html.ToString()
    End Sub
End Class