Namespace ExpertChoice.Data

    Public Module PagesList

#Region "Pages"

        Public Const _PGTITLE_PREFIX As String = "title"
        Public Const _PGMENU_PREFIX As String = "mnu"
        Public Const _PGHOTKEY_PREFIX As String = "shortcut"    ' D6995

        'Public Const _DEF_PGID_ONSILVERLIGHTPROJECTS As Integer = _PGID_PROJECTSLIST       ' D0754
        Public Const _DEF_PGID_ONSELECTPROJECT As Integer = _PGID_LANDING_STRUCTURE         ' D0072 + D0074 + D4645 + A1593 + D6060
        Public Const _DEF_PGID_ONSELECTPROJECT_RISK As Integer = _PGID_LANDING_RISK_IDENTIFY        ' D6061
        Public Const _DEF_PGID_ONSELECTPROJECT_INFODOC As Integer = _PGID_PROJECT_DESCRIPTION       ' D6253
        Public Const _DEF_PGID_ONSELECTPROJECT_RISK_INFODOC As Integer = _PGID_PROJECT_DESCRIPTION  ' D6253
        Public Const _DEF_PGID_ONSELECTPROJECT_MYRISKREWARD As Integer = _PGID_STRUCTURE_MYRISKREWARD   ' D6799
        Public Const _DEF_PGID_ONPROJECTS As Integer = _PGID_PROJECTSLIST                   ' D0492
        'Public Const _DEF_PGID_ONMANAGEPROJECTS As Integer = _PGID_PROJECTSLIST            ' D0492
        'Public Const _DEF_PGID_ONEVALUATEPROJECTSLIST As Integer = _PGID_PROJECTSLIST_EVALUATE ' D0089 + D0492 + D0818
        Public Const _DEF_PGID_ONEVALUATEPROJECT As Integer = _PGID_EVALUATION              ' D0818
        Public Const _DEF_PGID_ONNEWPROJECT As Integer = _PGID_PROJECT_DESCRIPTION          ' D0112 + D6060 + D6323 + D6483
        Public Const _DEF_PGID_ONNEWPROJECT_RISK As Integer = _PGID_PROJECT_DESCRIPTION     ' D6061 + D6323
        Public Const _DEF_PGID_ONNEW_BOGGSAT As Integer = _PGID_ANTIGUA_MEETING                 ' D66348
        Public Const _DEF_PGID_ONNEW_BOGGSAT_RISK As Integer = _PGID_ANTIGUA_MEETING_LIKELIHOOD ' D6348
        Public Const _DEF_PGID_ONNEW_MYRISKREWARD As Integer = _PGID_PROJECT_DESCRIPTION '_PGID_STRUCTURE_MYRISKREWARD ' D6799 + A2105
        Public Const _DEF_PGID_ONVIEWPROJECT As Integer = _PGID_ANALYSIS_OVERALL_ALTS       ' D6060 + D6390
        Public Const _DEF_PGID_ONSYSTEMWORKGROUP As Integer = _PGID_ADMIN_WORKGROUPS        ' D0089

        Public Const _DEF_MASTER_COMPARION As String = "choice project with few alternatives"
        Public Const _DEF_MASTER_RISKION As String = "risk"

        ' D0652 ===
        'Public Const _THEME_DEFAULT As String = "default"  ' -D4961
        Public Const _THEME_EC2018 As String = "ec2018" ' D4668
        Public Const _THEME_EC09 As String = "ec09"    ' -D4961
        Public Const _THEME_SL As String = "sl"         ' D0766
        Public Const _THEME_TT As String = "tt"         ' D0766

        'Public _THEMES_LIST() As String = {_THEME_DEFAULT, _THEME_EC09} ' D0653
        Public _THEMES_LIST() As String = {}    ' D0653 + D0779
        Public _THEMES_DRAFT() As String = {}   ' D0653

        Public Const _MASTER_DEFAULT As String = "mpDesktop.master"     ' -D4961
        Public Const _MASTER_EC2018 As String = "mpDesktop.master"      ' D4668
        'Public Const _MASTER_EC09 As String = "mpEC09.master"          ' -D4961
        Public Const _MASTER_EC09_TT As String = "mpEC09_TT.master"     ' D0766
        'Public Const _MASTER_BLANK As String = "mpBlank.master"        ' -D4961
        Public Const _MASTER_EMPTY As String = "mpEmpty.master"
        Public Const _MASTER_WEBAPI As String = "mpWebAPI.master"       ' D5025
        Public Const _MASTER_POPUP As String = "mpPopup.master"
        ' D0652 ==

        ' D0286 ===
        Public _PAGESLIST_SPYRON() As Integer = {_PGID_SURVEY_EDIT_PRE, _PGID_SURVEY_EDIT_POST, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_NEW, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_SURVEY_UPLOAD}   ' D0644 + D1333 + D1962 + D2780
        'Public _PAGESLIST_ANTIGUA() As Integer = {_PGID_ANTIGUA_ADMIN, _PGID_ANTIGUA_MEETING, _PGID_ANTIGUA_MEETING_IMPACT, _PGID_ANTIGUA_MEETING_LIKELIHOOD}    ' D6239
        Public _PAGESLIST_ANTIGUA() As Integer = {_PGID_ANTIGUA_MEETING, _PGID_ANTIGUA_MEETING_IMPACT, _PGID_ANTIGUA_MEETING_LIKELIHOOD}    ' D6239
        Public _PAGESLIST_TEAMTIME() As Integer = {_PGID_TEAMTIME, _PGID_TEAMTIME_INVITE, _PGID_TEAMTIME_STATUS, _PGID_TEAMTIME_USERS}    ' D0391 + D0432 + D0439 + D0584 + D0625 + D0638 + D1238 + D1440 + D4314 + D6096 // don't include _PGID_EVALUATE_TEAMTIME_CV
        'Public _PAGESLIST_ARCHIVED_ONLY() As Integer = {_PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_EVAL_PROGRESS, _PGID_MEASURE_EVAL_PROGRESS, _PGID_PROJECT_STATUS, _PGID_PROJECT_UPDATE, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_ALTSCONTRIB, _PGID_STRUCTURE_PERMISSION_ALTS, _PGID_PROJECT_USERS, _PGID_EVALUATE_INFODOC, _PGID_UNKNOWN, _PGID_SURVEY_EDIT, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_EVALUATE_INFODOC, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_RA_STRATEGIC_BUCKETS, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_INFODOCS, _PGID_ANALYSIS_2D, _PGID_ANALYSIS_OVERALL_ALTS, _PGID_ANALYSIS_CONSENSUS, _PGID_ANALYSIS_DSA, _PGID_ANALYSIS_GSA, _PGID_ANALYSIS_HEAD2HEAD, _PGID_ANALYSIS_ASA, _PGID_ANALYSIS_4ASA, _PGID_ANALYSIS_OVERALL_OBJS, _PGID_ANALYSIS_PSA, _PGID_ANALYSIS_OVERALL_ALTS_CHART, _PGID_ANALYSIS_OVERALL_OBJS_CHART, _PGID_STRUCTURE_MEASUREMENT_METHODS}    ' D0310 + D0323 + D0357 + D0638 + D0641 + D0654 + D0788 + D2495 + D2780 + D3434 + D3564 + A1080 + A1083 + A1216 + A1217 + A1475
        Public _PAGESLIST_ARCHIVED_ONLY() As Integer = {_PGID_LANDING_COMMON, _PGID_LANDING_RESULTS, _PGID_LANDING_MEASURE, _PGID_LANDING_RESULTS, _PGID_LANDING_RISK_IDENTIFY, _PGID_LANDING_STRUCTURE, _PGID_WEBAPI, _PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_EVAL_PROGRESS, _PGID_MEASURE_EVAL_PROGRESS, _PGID_CONTROLS_EVAL_PROGRESS, _PGID_REPORT_DATAGRID, _PGID_REPORT_DATAGRID2, _PGID_REPORT_DATAGRID_NOUPLOAD, _PGID_REPORT_DATAGRID_RISK, _PGID_REPORT_DATAGRID_RISK_TREATMENTS, _PGID_PROJECT_UPDATE, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_SOURCES, _PGID_STRUCTURE_OBJECTIVES, _PGID_STRUCTURE_SOURCES_HIERARCHY, _PGID_STRUCTURE_SOURCES_CONTRIBUTIONS, _PGID_STRUCTURE_OBJECTIVES_HIERARCHY, _PGID_STRUCTURE_OBJECTIVES_CONTRIBUTIONS, _PGID_STRUCTURE_INFODOCS, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_STRUCTURE_MEASUREMENT_METHODS_ALTS, _PGID_STRUCTURE_MEASUREMENT_METHODS_OBJS, _PGID_STRUCTURE_MYRISKREWARD, _PGID_STRUCTURE_ALTSCONTRIB, _PGID_STRUCTURE_PERMISSION_ALTS, _PGID_STRUCTURE_MYRISKREWARD, _PGID_PROJECT_USERS, _PGID_EVALUATE_INFODOC, _PGID_UNKNOWN, _PGID_SURVEY_EDIT_PRE, _PGID_SURVEY_EDIT_POST, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_EVALUATE_INFODOC, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_INFODOCS, _PGID_ANALYSIS_2D, _PGID_ANALYSIS_OVERALL_ALTS, _PGID_ANALYSIS_CONSENSUS, _PGID_ANALYSIS_DSA, _PGID_ANALYSIS_GSA, _PGID_ANALYSIS_HEAD2HEAD, _PGID_ANALYSIS_ASA, _PGID_ANALYSIS_4ASA, _PGID_ANALYSIS_OVERALL_OBJS, _PGID_ANALYSIS_PSA, _PGID_ANALYSIS_OVERALL_ALTS_CHART, _PGID_ANALYSIS_OVERALL_OBJS_CHART, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_ANALYSIS_CHARTS_ALTS, _PGID_ANALYSIS_CHARTS_OBJS, _PGID_ANALYSIS_GRIDS, _PGID_ANALYSIS_GRIDS_ALTS, _PGID_ANALYSIS_GRIDS_OBJS}    ' D0310 + D0323 + D0357 + D0638 + D0641 + D0654 + D0788 + D2495 + D2780 + D3434 + D3564 + A1080 + A1083 + A1216 + A1217 + A1475 + D5092 + D6091 + D6096 + D6258 + D6799 + D6965 + D7457
        Public _PAGESLIST_EXPORTS() As Integer = {_PGID_ADMIN_LOGINS_STAT} ' D0919 + D0920 + D0923
        'Public _PAGESLIST_TEMPLATE() As Integer = {_PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_STATUS, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_PROJECT_UPDATE, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_ALTSCONTRIB, _PGID_UNKNOWN, _PGID_SURVEY_EDIT, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_EVALUATE_INFODOC, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_RA_STRATEGIC_BUCKETS, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_INFODOCS, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_RISK_EVENTS, _PGID_RISK_EVENT_GROUPS, _PGID_BAYESIAN_UPDATING}    ' D0580 + D0654 + D2495 + D2561 + D2780 + D3434 + A1080 + A1083 + A1217 + A1475
        Public _PAGESLIST_TEMPLATE() As Integer = {_PGID_LANDING_COMMON, _PGID_LANDING_STRUCTURE, _PGID_LANDING_RISK_IDENTIFY, _PGID_WORKFLOW_RISK_DEFINE_MODEL, _PGID_WEBAPI, _PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_PROJECT_UPDATE, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_ALTSCONTRIB, _PGID_UNKNOWN, _PGID_SURVEY_EDIT_PRE, _PGID_SURVEY_EDIT_POST, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_EVALUATE_INFODOC, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_STRUCTURE_ALTERNATIVES, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_SOURCES, _PGID_STRUCTURE_OBJECTIVES, _PGID_STRUCTURE_SOURCES_HIERARCHY, _PGID_STRUCTURE_SOURCES_CONTRIBUTIONS, _PGID_STRUCTURE_OBJECTIVES_HIERARCHY, _PGID_STRUCTURE_OBJECTIVES_CONTRIBUTIONS, _PGID_STRUCTURE_INFODOCS, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_STRUCTURE_MEASUREMENT_METHODS_ALTS, _PGID_STRUCTURE_MEASUREMENT_METHODS_OBJS, _PGID_STRUCTURE_MYRISKREWARD, _PGID_RISK_EVENTS, _PGID_RISK_EVENT_GROUPS, _PGID_BAYESIAN_UPDATING, _PGID_RISK_EVENTS, _PGID_RISK_EVENT_GROUPS, _PGID_RISK_THREAT_GROUPS}    ' D0580 + D0654 + D2495 + D2561 + D2780 + D3434 + A1080 + A1083 + A1217 + A1475 + D5092 + D6091 + D6096 + D6120 + D7457
        'Public _PAGESLIST_MASTERPROJECTS() As Integer = {_PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_STATUS, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_UPDATE, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_SERVICEPAGE, _PGID_SURVEY_EDIT, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_NEW, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_SURVEY_UPLOAD, _PGID_RICHEDITOR, _PGID_UNKNOWN, _PGID_EVALUATE_INTENSITIES, _PGID_EVALUATE_INFODOC, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT, _PGID_EVALUATE_INTENSITIES}    ' D2479 + D2492 + D2506 + D2561 + D2780 + D3434 + A1047 + A1073 + A1083 + A1217 + A1231 + D4560
        Public _PAGESLIST_MASTERPROJECTS() As Integer = {_PGID_LANDING_COMMON, _PGID_LANDING_STRUCTURE, _PGID_LANDING_RISK_IDENTIFY, _PGID_WORKFLOW_RISK_DEFINE_MODEL, _PGID_WEBAPI, _PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_UPDATE, _PGID_PROJECT_COPY, _PGID_PROJECT_CREATE_FROM_TPL, _PGID_PROJECT_DELETE, _PGID_STRUCTURE_HIERARCHY, _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT, _PGID_SERVICEPAGE, _PGID_SURVEY_EDIT_PRE, _PGID_SURVEY_EDIT_POST, _PGID_SURVEY_QUESTION_EDIT, _PGID_SURVEY_QUESTION_NEW, _PGID_SURVEY_QUESTION_EDITOR, _PGID_SURVEY_DOWNLOAD, _PGID_SURVEY_GROUP_FILTER, _PGID_SURVEY_RESULTS, _PGID_SURVEY_UPLOAD, _PGID_RICHEDITOR, _PGID_UNKNOWN, _PGID_EVALUATE_INTENSITIES, _PGID_EVALUATE_INFODOC, _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY, _PGID_STRUCTURE_MEASUREMENT_METHODS, _PGID_EVALUATE_INTENSITIES}    ' D2479 + D2492 + D2506 + D2561 + D2780 + D3434 + A1047 + A1073 + A1083 + A1217 + A1231 + D4560 + D5092 + D6091 + D6096
        'Public _PAGESLIST_DELETED() As Integer = {_PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_EVALUATE_INFODOC, _PGID_PROJECT_DELETE, _PGID_PROJECT_UNDELETE, _PGID_PROJECT_STATUS, _PGID_UNKNOWN}    ' D0789 + A1217
        Public _PAGESLIST_DELETED() As Integer = {_PGID_LANDING_COMMON, _PGID_LANDING_RESULTS, _PGID_LANDING_RISK_IDENTIFY, _PGID_LANDING_STRUCTURE, _PGID_WEBAPI, _PGID_PROJECT_DESCRIPTION, _PGID_PROJECT_PROPERTIES, _PGID_EVALUATE_INFODOC, _PGID_PROJECT_DELETE, _PGID_UNKNOWN}    ' D0789 + A1217 + D5092 + D6091 + D6096
        Public _PAGESLIST_RA() As Integer = {_PGID_LANDING_ALLOCATE, _PGID_RA_BASE, _PGID_RA_TIMEPERIODS_SETTINGS, _PGID_RA_DEPENDENCIES, _PGID_RA_DOWNLOAD, _PGID_RA_FUNDINGPOOLS, _PGID_RA_GROUPS, _PGID_RISK_THREAT_GROUPS, _PGID_RISK_EVENT_GROUPS, _PGID_RISK_THREAT_GROUPS, _PGID_RA_INC_BUDGETS, _PGID_RA_PLOT_ALTS, _PGID_RA_REPORT, _PGID_RA_REPORT_MODEL_SPEC, _PGID_RA_REPORT_CONSTR_SUMMARY, _PGID_RA_REPORT_RELEVANT_CONSTR, _PGID_RA_SCENARIOS, _PGID_RA_STRATEGIC_BUCKETS, _PGID_RA_REPORT_SOLVER_REPORT, _PGID_RA_PERIOD_RESULTS}  ' D2922 + D3197 + A0969 + D3434 + A1035 + D7079
        'Public _PAGESLIST_RA() As Integer = {_PGID_LANDING_ALLOCATE, _PGID_RA_BASE, _PGID_RA_TIMEPERIODS_SETTINGS, _PGID_RA_DEPENDENCIES, _PGID_RA_DOWNLOAD, _PGID_RA_FUNDINGPOOLS, _PGID_RA_GROUPS, _PGID_RISK_THREAT_GROUPS, _PGID_RISK_EVENT_GROUPS, _PGID_RISK_THREAT_GROUPS, _PGID_RA_INC_BUDGETS, _PGID_RA_PLOT_ALTS, _PGID_RA_REPORT, _PGID_RA_REPORT_MODEL_SPEC, _PGID_RA_REPORT_CONSTR_SUMMARY, _PGID_RA_REPORT_RELEVANT_CONSTR, _PGID_RA_SCENARIOS, _PGID_RA_STRATEGIC_BUCKETS, _PGID_RA_REPORT_SOLVER_REPORT, _PGID_RA_PORTFOLIO_RESOURCES, _PGID_RA_PERIOD_RESULTS, _PGID_RA_PROJECT_RESOURCES}  ' D2922 + D3197 + A0969 + D3434 + A1035
        'Public _PAGESLIST_RA_TIMEPERIODS() As Integer = {_PGID_RA_TIMEPERIODS_SETTINGS, _PGID_RA_PORTFOLIO_RESOURCES, _PGID_RA_PERIOD_RESULTS, _PGID_RA_PROJECT_RESOURCES}   ' D3725
        Public _PAGESLIST_RA_TIMEPERIODS() As Integer = {_PGID_RA_TIMEPERIODS_SETTINGS, _PGID_RA_PERIOD_RESULTS}   ' D3725 + D7079
        ' D0286 ==

        Public _PAGESLIST_DRAFT() As Integer = {_PGID_ADMIN_ROLEGROUPS, _PGID_TEST, _PGID_REPORT_MAXOUT, _PGID_ADMIN_GENERATE_USER, _PGID_DB_SQL}   ' D0197 ... D0530 + D0618 + D0635 + D0640 + D0652 + D0660 + D0674 + D0675 + D0920 + D1399 + D3661 + D3725 + D4101 + D5008

        'Public _PAGESLIST_SKIP_LASTVISITED() As Integer = {_PGID_UNKNOWN, _PGID_LOGOUT, _PGID_ERROR_403, _PGID_ERROR_404, _PGID_ERROR_500, _PGID_ERROR_503, _PGID_START, _PGID_START_WITH_SIGNUP, _PGID_WORKGROUP_SELECT, _PGID_EULA, _PGID_ACCOUNT_FORGOTTEN, _PGID_CUSTOMER_SUPPORT, _PGID_RICHEDITOR, _PGID_PROJECT_UPDATE, _PGID_SERVICEPAGE, _PGID_EVALUATE_INFODOC, _PGID_EVALUATE_INTENSITIES, _PGID_CREATE_PASSWORD, _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT, _PGID_PROJECT_SNAPSHOTS, _PGID_LANDING_PAGE} ' D0491 + D0493 + D0529 + D0625 + D0725 + D0788 + D0871 + D1056 -D1399 + D1807 + D2215 + A1231 + D4705
        Public _PAGESLIST_SKIP_LASTVISITED() As Integer = {_PGID_UNKNOWN, _PGID_LOGOUT, _PGID_ERROR_403, _PGID_ERROR_404, _PGID_ERROR_500, _PGID_ERROR_503, _PGID_START, _PGID_START_WITH_SIGNUP, _PGID_EULA, _PGID_CUSTOMER_SUPPORT, _PGID_RICHEDITOR, _PGID_PROJECT_UPDATE, _PGID_SERVICEPAGE, _PGID_EVALUATE_INFODOC, _PGID_EVALUATE_INTENSITIES, _PGID_TEAMTIME, _PGID_TEAMTIME_CV, _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT, _PGID_PROJECT_SNAPSHOTS, _PGID_INFO_PAGE, _PGID_PING, _PGID_WEBAPI, _PGID_WEBAPI_HELP, _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT, _PGID_PROJECT_SNAPSHOTS, _PGID_DB_SETUP, _PGID_DB_DECISIONS, _PGID_SYSTEM_SETTINGS, _PGID_PINCODE, _PGID_FEDRAMP_NOTIFICATION, _PGID_JS_RESOURCES, _PGID_SEND_MAIL, _PGID_SSO_ASSERT, _PGID_REPORT_DATAGRID_UPLOAD} ' D0491 + D0493 + D0529 + D0625 + D0725 + D0788 + D0871 + D1056 -D1399 + D1807 + D2215 + A1231 + D4705 + D4842 + D4866 + D5005 + D5013 + D6081 + D6516 + D6552 + D7087 + D7178 + D7621

        Public _PAGESLIST_PASSCODE_ONLY() As Integer = {_PGID_CUSTOMER_SUPPORT, _PGID_EULA, _PGID_ACCOUNT_EDIT, _PGID_CREATE_PASSWORD,
                                                        _PGID_SILVERLIGHT_UI, _PGID_SERVICEPAGE,
                                                        _PGID_ERROR_403, _PGID_ERROR_404, _PGID_ERROR_500, _PGID_INFO_PAGE,
                                                        _PGID_ERROR_503, _PGID_PROJECT_UPDATE,
                                                        _PGID_EVALUATION, _PGID_EVALUATION, _PGID_EVALUATE_RISK_CONTROLS, _PGID_ANALYSIS_RISK_RESULTS_ALL_EVENTS, _PGID_TEAMTIME, _PGID_TEAMTIME_CV, _PGID_EVALUATE_INFODOC, _PGID_RICHEDITOR,
                                                        _PGID_UNKNOWN, _PGID_LOGOUT, _PGID_START, _PGID_START_WITH_SIGNUP,
                                                        _PGID_PROJECT_OPTION_EVALUATE, _PGID_PROJECT_OPTION_NAVIGATE, _PGID_PROJECT_OPTION_DISPLAY, _PGID_PROJECT_OPTION_SURVEY}     ' D0390 + D0429 + D0438 + D0443 + D0492 + D0509 + D0522 + D0532 +  D0788 (-_PGID_PROJECTSLIST_EVALUATE, _PGID_PROJECTSLIST) + D0840 + D0866 + D0883 (-_PGID_FEEDBACK) + D1056 + D1183 + D1238 + D1399 + D1547 + D2215 + D2261 + D2811 + D2955 + D3365 + D3563 + D4705 + D4866

        ' D3853 ===
        Public _PAGESLIST_RESULTS() As Integer = {_PGID_ANALYSIS_OVERALL_ALTS, _PGID_ANALYSIS_OVERALL_OBJS, _PGID_ANALYSIS_OVERALL_ALTS_CHART,
                                                  _PGID_ANALYSIS_OVERALL_OBJS_CHART, _PGID_ANALYSIS_DSA, _PGID_ANALYSIS_PSA,
                                                  _PGID_ANALYSIS_GSA, _PGID_ANALYSIS_2D, _PGID_ANALYSIS_CONSENSUS,
                                                  _PGID_ANALYSIS_HEAD2HEAD, _PGID_REPORT_DATAGRID_NOUPLOAD, _PGID_ANALYSIS_ASA, _PGID_ANALYSIS_4ASA,
                                                  _PGID_ANALYSIS_DASHBOARD, _PGID_ANALYSIS_CHARTS_ALTS, _PGID_ANALYSIS_CHARTS_OBJS,
                                                  _PGID_ANALYSIS_GRIDS, _PGID_ANALYSIS_GRIDS_ALTS, _PGID_ANALYSIS_GRIDS_OBJS}  ' D6258

        Public _PAGESLIST_RISK() As Integer = {_PGID_ANALYSIS_RISK_RESULTS_ALL_EVENTS, _PGID_ANALYSIS_RISK_RESULTS_SPECIFIC_CAUSES,
                                               _PGID_ANALYSIS_RISK_RESULTS_SPECIFIC_OBJS, _PGID_ANALYSIS_RISK_RESULTS_ALL_CAUSES,
                                               _PGID_ANALYSIS_RISK_RESULTS_ALL_OBJS,
                                               _PGID_RISK_PLOT_CAUSES, _PGID_RISK_PLOT_OVERALL, _PGID_RISK_PLOT_OBJECTIVES,
                                               _PGID_RISK_BOW_TIE, _PGID_RISK_BOW_TIE_CAUSES, _PGID_RISK_BOW_TIE_OBJS,
                                               _PGID_REPORT_DATAGRID_RISK}

        Public _PAGESLIST_TREATMENTS() As Integer = {_PGID_RISK_TREATMENTS_MAP_CAUSES, _PGID_RISK_TREATMENTS_MAP_VULNERABILITIES,
                                                     _PGID_RISK_TREATMENTS_MAP_CONSEQUENCES, _PGID_RISK_TREATMENTS_MAP_VULNERABILITIES_BY_TREATMENT,
                                                     _PGID_RISK_TREATMENTS_MAP_CONSEQUENCES_BY_TREATMENT,
                                                     _PGID_RISK_TREATMENTS_MEASURE_CAUSES, _PGID_RISK_TREATMENTS_MEASURE_VULNERABILITIES,
                                                     _PGID_RISK_TREATMENTS_MEASURE_CONSEQUENCES, _PGID_RISK_TREATMENTS_MEASURE_VULNERABILITIES_BY_TREATMENT,
                                                     _PGID_RISK_TREATMENTS_MEASURE_CONSEQUENCES_BY_TREATMENT,
                                                     _PGID_RISK_INVITE_USERS, _PGID_RISK_ROLES,
                                                     _PGID_CONTROLS_EVAL_PROGRESS,
                                                     _PGID_EVALUATE_RISK_CONTROLS, _PGID_EVALUATE_RISK_CONTROLS_READONLY,
                                                     _PGID_RISK_TREATMENTS_EFFECT_CAUSES, _PGID_RISK_TREATMENTS_EFFECT_VULNERABILITIES,
                                                     _PGID_RISK_TREATMENTS_EFFECT_CONSEQUENCES, _PGID_RISK_TREATMENTS_EFFECT_VULNERABILITIES_BY_TREATMENT,
                                                     _PGID_RISK_TREATMENTS_EFFECT_CONSEQUENCES_BY_TREATMENT,
                                                     _PGID_RISK_SELECT_TREATMENTS, _PGID_RISK_TREATMENTS_REPORT_CAUSES,
                                                     _PGID_RISK_TREATMENTS_REPORT_VULNERABILITIES, _PGID_RISK_TREATMENTS_REPORT_CONSEQENCES,
                                                     _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_CAUSES, _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_OBJS,
                                                     _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_OVERALL, _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_ALL_CAUSES,
                                                     _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_ALL_OBJS,
                                                     _PGID_RISK_BOW_TIE_WITH_CONTROLS_MENU, _PGID_RISK_BOW_TIE_WITH_CONTROLS,
                                                     _PGID_RISK_BOW_TIE_WITH_CONTROLS_CAUSES, _PGID_RISK_BOW_TIE_WITH_CONTROLS_OBJS,
                                                     _PGID_RISK_PLOT_OVERALL_WITH_CONTROLS, _PGID_RISK_PLOT_CAUSES_WITH_CONTROLS,
                                                     _PGID_RISK_PLOT_OBJECTIVES_WITH_CONTROLS,
                                                     _PGID_REPORT_DATAGRID_RISK_TREATMENTS,
                                                     _PGID_RISK_REGISTER_WITH_CONTROLS, _PGID_RISK_TREATMENTS_REGISTER, _PGID_RISK_ACCEPTANCE_REGISTER, _PGID_RISK_TREATMENTS_DICTIONARY, _PGID_RISK_OPTIMIZER} ' D4285 + A1353
        ' D3853 ==

        Public _PAGESLIST_IGNORE_PING() As Integer = {_PGID_UNKNOWN, _PGID_PING, _PGID_WEBAPI, _PGID_WEBAPI_HELP, _PGID_START, _PGID_START_WITH_SIGNUP, _PGID_TEST,
                                                      _PGID_SERVICEPAGE, _PGID_SILVERLIGHT_UI, _PGID_TEAMTIME,
                                                      _PGID_RA_BASE, _PGID_RA_DOWNLOAD, _PGID_RA_SCENARIOS, _PGID_RA_STRATEGIC_BUCKETS,
                                                      _PGID_PROJECT_DOWNLOAD, _PGID_PROJECT_UPDATE, _PGID_PROJECT_UPLOAD, _PGID_PROJECT_LOGS,
                                                      _PGID_PROJECT_SNAPSHOTS, _PGID_ADMIN_ONLINE_USERS, _PGID_ADMIN_VIEWLOGS, _PGID_ERROR_403,
                                                      _PGID_ERROR_404, _PGID_ERROR_500, _PGID_ERROR_503}  ' D4032 + D5013 + D5071

        Public _PAGESLIST_RISK_SENSITIVITIES() As Integer = {_PGID_RISK_DSA_LIKELIHOOD, _PGID_RISK_DSA_IMPACT, _PGID_RISK_DSA_LIKELIHOOD_WITH_CONTROLS, _PGID_RISK_DSA_IMPACT_WITH_CONTROLS, _PGID_RISK_PSA_LIKELIHOOD, _PGID_RISK_PSA_IMPACT, _PGID_RISK_PSA_LIKELIHOOD_WITH_CONTROLS, _PGID_RISK_PSA_IMPACT_WITH_CONTROLS} 'A2104

        '#Region "Tabs 0000*" 'A1450
        '        Public Const _PGID_TAB_HOME As Integer = 1
        '        Public Const _PGID_TAB_MANAGE As Integer = 2
        '        Public Const _PGID_TAB_EVENTS As Integer = 3
        '        Public Const _PGID_TAB_LIKELIHOOD As Integer = 4
        '        Public Const _PGID_TAB_IMPACT As Integer = 5
        '        Public Const _PGID_TAB_RISK As Integer = 6
        '        Public Const _PGID_TAB_CONTROLS As Integer = 7
        '        Public Const _PGID_TAB_OPTIMIZE As Integer = 8
        '#End Region

        Public Const _PGID_MAX_MOD As Integer = 100000 ' D5057

#Region "Common pages for everyone 1****"
        Public Const _PGID_START As Integer = 10001
        'Public Const _PGID_START_MEETING_ID As Integer = 10003  ' D0391 -D0439
        Public Const _PGID_LOGOUT As Integer = 10002
        Public Const _PGID_SSO_ASSERT As Integer = 10008        ' D6550
        Public Const _PGID_START_WITH_SIGNUP As Integer = 10009 ' D1056
        'Public Const _PGID_ABOUT As Integer = 10010 ' D0089
        Public Const _PGID_EULA As Integer = 10020  ' D0272
        Public Const _PGID_FEDRAMP_NOTIFICATION As Integer = 10021  ' D6081
        Public Const _PGID_RESOURCE_CENTER As Integer = 10060   ' D0425 -D1841 - D2811
        'Public Const _PGID_SAMPLES As Integer = 10065   ' D0866
        Public Const _PGID_CUSTOMER_SUPPORT As Integer = 10070  ' D0407
        Public Const _PGID_SEND_MAIL As Integer = 10071  ' D3579
        'Public Const _PGID_PRODUCT_DOCUMENTS As Integer = 10080 ' D0320 -D0425
        Public Const _PGID_KNOWN_ISSUES As Integer = 10090  ' D6028
        Public Const _PGID_INFO_PAGE As Integer = 10099  ' D4705
        ' D4994 ===
        Public Const _PGID_LANDING_COMMON As Integer = 10100
        Public Const _PGID_LANDING_STRUCTURE As Integer = 10101
        Public Const _PGID_LANDING_MEASURE As Integer = 10102
        Public Const _PGID_LANDING_RESULTS As Integer = 10103
        Public Const _PGID_LANDING_ALLOCATE As Integer = 10104
        Public Const _PGID_LANDING_REPORTS As Integer = 10105
        Public Const _PGID_LANDING_RISK_IDENTIFY As Integer = 10201
        Public Const _PGID_WORKFLOW_RISK_DEFINE_MODEL As Integer = 20017
        ' D4994 ==
        'Public Const _PGID_HELP As Integer = 10090  ' D0144
        'Public Const _PGID_VIDEO_HELP As Integer = 10091    ' D0311
#End Region

#Region "Pages for work with projects 2****"
        Public Const _PGID_PROJECTSLIST As Integer = 20001
        Public Const _PGID_PROJECTSLIST_ARCHIVED As Integer = 20003         ' D0058
        Public Const _PGID_PROJECTSLIST_TEMPLATES As Integer = 20005        ' D0206
        Public Const _PGID_PROJECTSLIST_MASTERPROJECTS As Integer = 20006   ' D2479
        Public Const _PGID_PROJECTSLIST_DELETED As Integer = 20007          ' D0789
        Public Const _PGID_PROJECTSLIST_REVIEW As Integer = 20008           ' D4640
        'Public Const _PGID_PROJECTSLIST_STARRED As Integer = 20009          'A1715 + D5006 -D5013

        Public Const _PGID_PROJECT_DESCRIPTION As Integer = 20010       'A1593
        Public Const _PGID_PROJECT_PROPERTIES As Integer = 20011
        'Public Const _PGID_PROJECT_STATUS As Integer = 20018
        Public Const _PGID_PROJECT_OPTION_EVALUATE As Integer = 20013   ' D3624
        Public Const _PGID_PROJECT_OPTION_NAVIGATE As Integer = 20014   ' D3624
        Public Const _PGID_PROJECT_OPTION_DISPLAY As Integer = 20015    ' D3624
        Public Const _PGID_PROJECT_OPTION_SURVEY As Integer = 20016     ' D3624
        Public Const _PGID_PROJECT_USERS As Integer = 20020     ' D0052
        Public Const _PGID_PROJECT_SNAPSHOTS As Integer = 20030 ' D3558
        Public Const _PGID_PROJECT_LOGS As Integer = 20039      ' D3559
        Public Const _PGID_PROJECT_CREATE As Integer = 20050    ' D0045
        Public Const _PGID_PROJECT_UPLOAD As Integer = 20051    ' D0045
        Public Const _PGID_PROJECT_DELETE As Integer = 20052    ' D0052
        Public Const _PGID_PROJECT_COPY As Integer = 20053      ' D0130
        Public Const _PGID_PROJECT_CREATE_FROM_TPL As Integer = 20054   ' D0324
        'Public Const _PGID_PROJECT_UNLOCK As Integer = 20055    ' D0134
        'Public Const _PGID_PROJECT_LOCK As Integer = 20056      ' D0137
        'Public Const _PGID_PROJECT_UNDELETE As Integer = 20057  ' D0789
        Public Const _PGID_PROJECT_UPDATE As Integer = 20058    ' D0622
        Public Const _PGID_PROJECT_DOWNLOAD As Integer = 20059

        Public Const _PGID_STRUCTURE_HIERARCHY As Integer = 20101
        Public Const _PGID_STRUCTURE_ALTERNATIVES As Integer = 20102
        Public Const _PGID_STRUCTURE_SOURCES As Integer = 20103
        Public Const _PGID_STRUCTURE_OBJECTIVES As Integer = 20104
        Public Const _PGID_STRUCTURE_SOURCES_HIERARCHY As Integer = 20108
        Public Const _PGID_STRUCTURE_SOURCES_CONTRIBUTIONS As Integer = 20118
        Public Const _PGID_STRUCTURE_OBJECTIVES_HIERARCHY As Integer = 20109
        Public Const _PGID_STRUCTURE_OBJECTIVES_CONTRIBUTIONS As Integer = 20119
        Public Const _PGID_STRUCTURE_ALTSCONTRIB As Integer = 20111
        Public Const _PGID_STRUCTURE_INFODOCS As Integer = 20112
        'Public Const _PGID_MAP_GRID_VIEW_RISK As Integer = 20113
        'Public Const _PGID_STRUCTURE_DEFINEMEASUREMENT As Integer = 20120
        Public Const _PGID_STRUCTURE_MEASUREMENT_METHODS As Integer = 20123 'A1083 html version
        Public Const _PGID_STRUCTURE_MEASUREMENT_METHODS_ALTS As Integer = 20121
        Public Const _PGID_STRUCTURE_MEASUREMENT_METHODS_OBJS As Integer = 20122
        'Public Const _PGID_STRUCTURE_MEASUREMENT_SCALES_ALL As Integer = 20150 'A1045
        Public Const _PGID_STRUCTURE_MEASUREMENT_SCALES_DEFAULT As Integer = 20151 'A1045
        Public Const _PGID_BAYESIAN_UPDATING As Integer = 20129 'A1464
        Public Const _PGID_STRUCTURE_MYRISKREWARD As Integer = 20130

        'Public Const _PGID_STRUCTURE_PERMISSIONS As Integer = 20141
        Public Const _PGID_STRUCTURE_PERMISSION_ALTS As Integer = 20142
        Public Const _PGID_STRUCTURE_MISSING_ROLES_REPORT As Integer = 20143        ' D6092

        Public Const _PGID_RICHEDITOR As Integer = 20199 ' D0107

        ' D0074 ===
        'Public Const _PGID_PROJECT_OVERVIEW As Integer = 20200
        'Public Const _PGID_OVERVIEW_DESCRIPTION As Integer = 20207
        'Public Const _PGID_OVERVIEW_PURPOSE As Integer = 20201
        'Public Const _PGID_OVERVIEW_OBJECTIVES As Integer = 20202
        'Public Const _PGID_OVERVIEW_ALTERNATIVES As Integer = 20203
        'Public Const _PGID_OVERVIEW_CONTRIBUTION As Integer = 20204
        'Public Const _PGID_OVERVIEW_EVALUATORS As Integer = 20205
        'Public Const _PGID_OVERVIEW_INVITATIONS As Integer = 20206  ' D0299
        ' D0074 ==

        Public Const _PGID_RESULTGROUPS As Integer = 20500      ' D0675

        'Public Const _PGID_ANTIGUA_ADMIN As Integer = 20400     ' D0580
        Public Const _PGID_ANTIGUA_MEETING As Integer = 20450   ' D0585
        Public Const _PGID_ANTIGUA_MEETING_LIKELIHOOD As Integer = 20451
        Public Const _PGID_ANTIGUA_MEETING_IMPACT As Integer = 20452

        Public Const _PGID_PROJECT_EVAL_PROGRESS As Integer = 20061     'A1040
        Public Const _PGID_CONTROLS_EVAL_PROGRESS As Integer = 20062    'A1040
        Public Const _PGID_MEASURE_EVAL_PROGRESS As Integer = 20063     'A1044

        Public Const _PGID_MAP_DIAGRAM_VIEW_RISK As Integer = 20114     'A1161
        Public Const _PGID_MAP_DIAGRAM_VIEW_BY_OBJ_RISK As Integer = 20115 'A1161

#End Region

#Region "Pages, connected with evaluation 3****"
        Public Const _PGID_EVALUATION As Integer = 30010        ' D0072 + D0493
        'Public Const _PGID_EVALUATENOW As Integer = 30011       ' D0076
        'Public Const _PGID_EVALUATE_DATAINSTANCES As Integer = 30012    ' D0228
        Public Const _PGID_EVALUATE_INTENSITIES As Integer = 30014      ' D1800
        Public Const _PGID_EVALUATE_READONLY As Integer = 30015 ' D0309
        Public Const _PGID_EVALUATE_RISK_CONTROLS As Integer = 30016    ' D2052
        Public Const _PGID_EVALUATE_RISK_CONTROLS_READONLY As Integer = 30017   ' D4285
        Public Const _PGID_EVALUATE_INFODOC As Integer = 30019  ' D0787
        Public Const _PGID_EVALUATE_INVITE As Integer = 30020   ' D4705

        Public Const _PGID_TEAMTIME As Integer = 30100 ' D1234
        Public Const _PGID_TEAMTIME_CV As Integer = 30101      ' D3563
        Public Const _PGID_TEAMTIME_INVITE As Integer = 30120  ' D4705

        'Public Const _PGID_TEAMTIME_LIST As Integer = 30500      ' D0192
        'Public Const _PGID_TEAMTIME_SETTINGS As Integer = 30510  ' D0192
        'Public Const _PGID_TEAMTIME_RUN_SESSION As Integer = 30511      ' D0625 - D1440
        Public Const _PGID_TEAMTIME_STATUS As Integer = 30502 'A1217
        Public Const _PGID_TEAMTIME_USERS As Integer = 30503    ' D4705
        'Public Const _PGID_TEAMTIME_CHECK_PROJECT As Integer = 30515    ' D0432

#End Region

#Region "Pages, connected with accounts 4****"""
        Public Const _PGID_ACCOUNT_EDIT As Integer = 40010
        'Public Const _PGID_ACCOUNT_TEMPLATES As Integer = 40011
        Public Const _PGID_CREATE_PASSWORD As Integer = 40051   ' D2215
        'Public Const _PGID_WORKGROUP_SELECT As Integer = 40080  ' D0096 -D4842
        'Public Const _PGID_ACCOUNT_FORGOTTEN As Integer = 40090 ' D0080 -D4866
        Public Const _PGID_PINCODE As Integer = 40099   ' D7187
#End Region

#Region "Reports 5****"
        Public Const _PGID_REPORTS As Integer = 50000                       ' D0069
        Public Const _PGID_REPORT_GENERATOR As Integer = 50001              ' D6511
        Public Const _PGID_REPORT_STRUCTURE As Integer = 50002              ' D0050
        Public Const _PGID_REPORT_JUDGMENTS As Integer = 50003              ' D0054
        Public Const _PGID_REPORT_OBJECTIVES As Integer = 50004             ' D0062
        Public Const _PGID_REPORT_ALTERNATIVES As Integer = 50009           ' L0193
        Public Const _PGID_REPORT_OBJANDALTS As Integer = 50005             ' D0062
        Public Const _PGID_REPORT_OBJPRIORITIES As Integer = 50006          ' D0065
        Public Const _PGID_REPORT_OBJANDALTPRIORITIES As Integer = 50007    ' D0065
        Public Const _PGID_REPORT_OVERALLRESULTS As Integer = 50008         ' D0065
        Public Const _PGID_REPORT_USERSOVERALLRESULTS As Integer = 50011    ' L0390 + D3919
        Public Const _PGID_REPORT_JUDGMENTS_ALTS As Integer = 50010         ' D3703

        Public Const _PGID_REPORT_CUSTOM As Integer = 50100                 ' D0138
        Public Const _PGID_REPORT_CUSTOM_PRIORITY As Integer = 50101        ' D0707
        Public Const _PGID_REPORT_CUSTOM_JUDGMENTS As Integer = 50102       ' D0707
        Public Const _PGID_REPORT_CUSTOM_OBJ_PRIORITY As Integer = 50103    ' D4677
        Public Const _PGID_REPORT_CUSTOM_EVAL_PRG As Integer = 50104        ' D4677
        Public Const _PGID_REPORT_CUSTOM_INCONSIST As Integer = 50105       ' D4677
        Public Const _PGID_REPORT_CUSTOM_SURVEY As Integer = 50106          ' D4677
        Public Const _PGID_SYNTHESIZE_INCONSIST As Integer = 50115          ' D4785
        Public Const _PGID_SYNTHESIZE_SURVEY As Integer = 50116             ' D4785

        Public Const _PGID_REPORT_DATAGRID As Integer = 50108               ' D1559
        Public Const _PGID_REPORT_DATAGRID2 As Integer = 50180              ' A1588
        Public Const _PGID_REPORT_DATAGRID_NOUPLOAD As Integer = 50107      ' D3853
        Public Const _PGID_REPORT_GET_DATA As Integer = 50110               ' D2556
        Public Const _PGID_REPORT_CSV As Integer = 50113                    ' D6299
        Public Const _PGID_REPORT_DATAGRID_UPLOAD As Integer = 50109        ' D1492
        Public Const _PGID_REPORT_DATA_MAPPING As Integer = 50120           ' D4087

        Public Const _PGID_REPORT_COMBINED As Integer = 50130               ' D6329

        Public Const _PGID_REPORT_DATAGRID_RISK As Integer = 70015          ' D2310 // pef DA req for compatible with SL shell
        Public Const _PGID_REPORT_DATAGRID_RISK_TREATMENTS As Integer = 70615   ' D3853

        Public Const _PGID_REPORT_MAXOUT As Integer = 50200                 ' D0387

#End Region

#Region "See Results/Analysis 6****"

        ' -D3485
        'Public Const _PGID_ANALYSIS_ADVANCED As Integer = 60009     ' D0311
        ' D0556 + D3564 ===
        Public Const _PGID_ANALYSIS_OVERALL_ALTS As Integer = 60210
        Public Const _PGID_ANALYSIS_OVERALL_OBJS As Integer = 60211
        Public Const _PGID_ANALYSIS_OVERALL_ALTS_CHART As Integer = 60212 'A1058
        Public Const _PGID_ANALYSIS_OVERALL_OBJS_CHART As Integer = 60213 'A1058
        Public Const _PGID_ANALYSIS_DSA As Integer = 60202
        Public Const _PGID_ANALYSIS_PSA As Integer = 60203
        Public Const _PGID_ANALYSIS_GSA As Integer = 60204
        Public Const _PGID_ANALYSIS_2D As Integer = 60207        ' D0660
        Public Const _PGID_ANALYSIS_ASA As Integer = 60214       ' A1216
        Public Const _PGID_ANALYSIS_4ASA As Integer = 60217      ' A1216
        Public Const _PGID_ANALYSIS_CONSENSUS As Integer = 60209 ' D0618
        Public Const _PGID_ANALYSIS_HEAD2HEAD As Integer = 60215
        Public Const _PGID_ANALYSIS_MIXED As Integer = 60216     'A1450
        Public Const _PGID_ANALYSIS_DASHBOARD As Integer = 60219
        Public Const _PGID_ANALYSIS_GRIDS As Integer = 60220
        Public Const _PGID_ANALYSIS_CHARTS_ALTS As Integer = 60221  ' D6536
        Public Const _PGID_ANALYSIS_CHARTS_OBJS As Integer = 60222  ' D6536
        Public Const _PGID_ANALYSIS_GRIDS_ALTS As Integer = 60223
        Public Const _PGID_ANALYSIS_GRIDS_OBJS As Integer = 60224

        Public Const _PGID_EXPORT_CHARTS_ALTS As Integer = 60421 ' D6470
        Public Const _PGID_EXPORT_CHARTS_OBJS As Integer = 60422 ' D6470

        ' D0556 + D3564 ==

        'A1523 ===
        Public Const _PGID_RISK_DSA_LIKELIHOOD As Integer = 60262               '990002
        Public Const _PGID_RISK_DSA_IMPACT As Integer = 60263                   '990003
        Public Const _PGID_RISK_DSA_LIKELIHOOD_WITH_CONTROLS As Integer = 60272 '990092
        Public Const _PGID_RISK_DSA_IMPACT_WITH_CONTROLS As Integer = 60273     '990093
        'A1523 ==

        Public Const _PGID_RISK_PSA_LIKELIHOOD As Integer = 60264
        Public Const _PGID_RISK_PSA_IMPACT As Integer = 60265
        Public Const _PGID_RISK_PSA_LIKELIHOOD_WITH_CONTROLS As Integer = 60274
        Public Const _PGID_RISK_PSA_IMPACT_WITH_CONTROLS As Integer = 60275

        Public Const _PGID_SYNTHESIS_RESULTS As Integer = 60255 'A1023
        Public Const _PGID_DASHBOARDS As Integer = 50111 ' A1491

        Public Const _PGID_ANALYSIS_RISK_RESULTS_LIKELIHOOD_GRID As Integer = 60301    ' D2040
        Public Const _PGID_ANALYSIS_RISK_RESULTS_LIKELIHOOD_CHART As Integer = 60302   ' D2040
        Public Const _PGID_ANALYSIS_RISK_RESULTS_IMPACT_GRID As Integer = 60304        ' A0750
        Public Const _PGID_ANALYSIS_RISK_RESULTS_IMPACT_CHART As Integer = 60305       ' A0750

        Public Const _PGID_ANALYSIS_RISK_RESULTS_LIKELIHOOD_BY_EVENT As Integer = 60306 ' A0778
        Public Const _PGID_ANALYSIS_RISK_RESULTS_IMPACT_BY_EVENT As Integer = 60307     ' A0778

        'Public Const _PGID_ANALYSIS_RISK_RESULTS_ALL_EVENTS_4PIPE As Integer = 70020    'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_ALL_EVENTS As Integer = 70016         'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_SPECIFIC_CAUSES As Integer = 70017    'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_SPECIFIC_OBJS As Integer = 70018      'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_ALL_CAUSES As Integer = 70019         'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_ALL_OBJS As Integer = 70022           'A0783
        Public Const _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_CAUSES As Integer = 70611 'A0801
        Public Const _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_OBJS As Integer = 70612   'A0801
        Public Const _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_OVERALL As Integer = 70614 'A0803
        Public Const _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_ALL_CAUSES As Integer = 70619 'A0801
        Public Const _PGID_ANALYSIS_RISK_RESULTS_WITH_CONTROLS_ALL_OBJS As Integer = 70622   'A0801

        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT As Integer = 70640 'A1231
        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT_FROM_SOURCES As Integer = 70641
        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT_TO_OBJS As Integer = 70642
        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT_WITH_CONTROLS As Integer = 70645
        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT_WITH_CONTROLS_FROM_SOURCES As Integer = 70646
        Public Const _PGID_ANALYSIS_RISK_RESULTS_EXTRA_PLOT_WITH_CONTROLS_TO_OBJS As Integer = 70647

        Public Const _PGID_RISK_INVITE_USERS As Integer = 70401   'A0871
        Public Const _PGID_RISK_SELECT_TREATMENTS As Integer = 70801   'A0871
        'Public Const _PGID_RISK_TREATMENTS_REPORT As Integer = 70803   'A1011
        Public Const _PGID_RISK_TREATMENTS_REPORT_CAUSES As Integer = 70804   'A1011
        Public Const _PGID_RISK_TREATMENTS_REPORT_VULNERABILITIES As Integer = 70805   'A1011
        Public Const _PGID_RISK_TREATMENTS_REPORT_CONSEQENCES As Integer = 70806   'A1011
        Public Const _PGID_RISK_ROLES As Integer = 70402   'A0871
        Public Const _PGID_RISK_SOURCE_GROUPS As Integer = 70030
        Public Const _PGID_RISK_CONTROLS_DATAGRID As Integer = 70040
        Public Const _PGID_RISK_STANDALONE_REDUCTIONS_GRID As Integer = 70045
        ' D2699 ===
        Public Const _PGID_RA_BASE As Integer = 77100
        Public Const _PGID_RA_DEPENDENCIES As Integer = 77101   ' D2699
        Public Const _PGID_RA_FUNDINGPOOLS As Integer = 77102      ' D2699
        Public Const _PGID_RA_GROUPS As Integer = 77103
        Public Const _PGID_RA_CUSTOM_CONSTRAINTS As Integer = 77104
        Public Const _PGID_RA_INC_BUDGETS As Integer = 77105
        Public Const _PGID_RA_DOWNLOAD As Integer = 77109   ' D2905
        Public Const _PGID_RA_REPORT As Integer = 77111     ' D3195
        Public Const _PGID_RA_REPORT_MODEL_SPEC As Integer = 77112          ' A0969
        Public Const _PGID_RA_REPORT_CONSTR_SUMMARY As Integer = 77113      ' A0969
        Public Const _PGID_RA_REPORT_RELEVANT_CONSTR As Integer = 77114     ' A0969
        Public Const _PGID_RA_REPORT_SOLVER_REPORT As Integer = 77115       ' A0969
        Public Const _PGID_RA_TIMEPERIODS_SETTINGS As Integer = 77118
        Public Const _PGID_RA_TIMEPERIODS As Integer = 77119
        'Public Const _PGID_RA_PORTFOLIO_RESOURCES As Integer = 77122
        Public Const _PGID_RA_PERIOD_RESULTS As Integer = 77124
        'Public Const _PGID_RA_PROJECT_RESOURCES As Integer = 77125
        ' D2699 ==
        Public Const _PGID_RA_PLOT_ALTS As Integer = 77107  ' D2844
        Public Const _PGID_RA_STRATEGIC_BUCKETS As Integer = 77108  ' D2844
        Public Const _PGID_RA_SCENARIOS As Integer = 77117 ' A0878

        'A1407 ===
        Public Const _PGID_RISK_EVENTS As Integer = 70501
        Public Const _PGID_RISK_THREAT_GROUPS As Integer = 70502
        Public Const _PGID_RISK_EVENT_GROUPS As Integer = 70503
        Public Const _PGID_RISK_EVENT_DEPENDENCIES As Integer = 70504
        'A1407 ==
        Public Const _PGID_RISK_SIMULATION_GROUPS As Integer = 70510

        'A0875 ===
        Public Const _PGID_RISK_TREATMENTS_MAP_CAUSES As Integer = 70055
        Public Const _PGID_RISK_TREATMENTS_MAP_VULNERABILITIES As Integer = 70056
        Public Const _PGID_RISK_TREATMENTS_MAP_CONSEQUENCES As Integer = 70057
        Public Const _PGID_RISK_TREATMENTS_MAP_VULNERABILITIES_BY_TREATMENT As Integer = 70058
        Public Const _PGID_RISK_TREATMENTS_MAP_CONSEQUENCES_BY_TREATMENT As Integer = 70059

        Public Const _PGID_RISK_TREATMENTS_MEASURE_CAUSES As Integer = 70201
        Public Const _PGID_RISK_TREATMENTS_MEASURE_VULNERABILITIES As Integer = 70202
        Public Const _PGID_RISK_TREATMENTS_MEASURE_CONSEQUENCES As Integer = 70203
        Public Const _PGID_RISK_TREATMENTS_MEASURE_VULNERABILITIES_BY_TREATMENT As Integer = 70204
        Public Const _PGID_RISK_TREATMENTS_MEASURE_CONSEQUENCES_BY_TREATMENT As Integer = 70205

        Public Const _PGID_RISK_TREATMENTS_EFFECT_CAUSES As Integer = 70105
        Public Const _PGID_RISK_TREATMENTS_EFFECT_VULNERABILITIES As Integer = 70106
        Public Const _PGID_RISK_TREATMENTS_EFFECT_CONSEQUENCES As Integer = 70107
        Public Const _PGID_RISK_TREATMENTS_EFFECT_VULNERABILITIES_BY_TREATMENT As Integer = 70108
        Public Const _PGID_RISK_TREATMENTS_EFFECT_CONSEQUENCES_BY_TREATMENT As Integer = 70109
        'A0875 ==

        Public Const _PGID_RISK_OPTIMIZER As Integer = 77201 'A1220
        Public Const _PGID_RISK_OPTIMIZER_OVERALL As Integer = 77202
        Public Const _PGID_RISK_OPTIMIZER_FROM_SOURCES As Integer = 77203
        Public Const _PGID_RISK_OPTIMIZER_TO_OBJS As Integer = 77204
        Public Const _PGID_RISK_OPTIMIZER_TIME_PERIODS_VIEW As Integer = 77210
        Public Const _PGID_RISK_OPTIMIZER_DEPENDENCIES As Integer = 77991 'A1220
        Public Const _PGID_RISK_OPTIMIZER_GROUPS As Integer = 77993 'A1220
        Public Const _PGID_RISK_OPTIMIZER_EFFICIENT_FRONTIER As Integer = 77995 'A1229
        Public Const _PGID_RISK_OPTIMIZER_EFFICIENT_FRONTIER_OVERALL As Integer = 77996
        Public Const _PGID_RISK_OPTIMIZER_EFFICIENT_FRONTIER_FROM_SOURCES As Integer = 77997
        Public Const _PGID_RISK_OPTIMIZER_EFFICIENT_FRONTIER_TO_OBJS As Integer = 77999
        Public Const _PGID_RISK_OPTIMIZER_PLOT As Integer = 77907 'A1375
        Public Const _PGID_RISK_OPTIMIZER_FUNDING_POOLS As Integer = 77992 'A1389
        Public Const _PGID_RISK_OPTIMIZER_CUSTOM_CONSTRAINTS As Integer = 77994 'A1389
        Public Const _PGID_RISK_OPTIMIZER_TIME_PERIODS As Integer = 77998 'A1389

        'A0877 ===
        Public Const _PGID_RISK_PLOT_CAUSES As Integer = 70003
        Public Const _PGID_RISK_PLOT_OVERALL As Integer = 70005
        Public Const _PGID_RISK_PLOT_OBJECTIVES As Integer = 70004
        Public Const _PGID_RISK_PLOT_OVERALL_WITH_CONTROLS As Integer = 70635
        Public Const _PGID_RISK_PLOT_CAUSES_WITH_CONTROLS As Integer = 70633
        Public Const _PGID_RISK_PLOT_OBJECTIVES_WITH_CONTROLS As Integer = 70634
        'A0877 ==

        'A0885 ===
        Public Const _PGID_RISK_BOW_TIE_MENU As Integer = 70007
        Public Const _PGID_RISK_BOW_TIE As Integer = 70008
        Public Const _PGID_RISK_BOW_TIE_CAUSES As Integer = 70009
        Public Const _PGID_RISK_BOW_TIE_OBJS As Integer = 70010
        Public Const _PGID_RISK_BOW_TIE_DEFINE_CONTROLS_WORKFLOW As Integer = 70053
        Public Const _PGID_RISK_BOW_TIE_DEFINE_CONTROLS As Integer = 70054
        Public Const _PGID_RISK_BOW_TIE_WITH_CONTROLS_MENU As Integer = 70607
        Public Const _PGID_RISK_BOW_TIE_WITH_CONTROLS As Integer = 70608
        Public Const _PGID_RISK_BOW_TIE_WITH_CONTROLS_CAUSES As Integer = 70609
        Public Const _PGID_RISK_BOW_TIE_WITH_CONTROLS_OBJS As Integer = 70610
        'A0885 ==

        'A1061 ===
        Public Const _PGID_RISK_REGISTERS_WORKFLOW_DEFAULT As Integer = 70910 'A1453
        Public Const _PGID_RISK_REGISTER_DEFAULT As Integer = 70911 'A1453
        Public Const _PGID_RISK_REGISTERS_WORKFLOW As Integer = 70900
        Public Const _PGID_RISK_REGISTER_WITH_CONTROLS As Integer = 70901
        Public Const _PGID_RISK_TREATMENTS_REGISTER As Integer = 70902
        Public Const _PGID_RISK_ACCEPTANCE_REGISTER As Integer = 70903 'A1072
        Public Const _PGID_RISK_TREATMENTS_DICTIONARY As Integer = 70904 'A1353
        'A1061 ==

        'A1050 ===
        'Public Const _PGID_VISUAL_BRAINSTORMING_MENU As Integer = 70520
        'Public Const _PGID_VISUAL_BRAINSTORMING_INDIVIDUAL As Integer = 70521
        'Public Const _PGID_VISUAL_BRAINSTORMING_INVITE As Integer = 70522
        'Public Const _PGID_VISUAL_BRAINSTORMING_TEAMTIME As Integer = 70523
        'Public Const _PGID_VISUAL_STRUCTURING_MENU As Integer = 70530
        'Public Const _PGID_VISUAL_STRUCTURING_INDIVIDUAL As Integer = 70531
        'Public Const _PGID_VISUAL_STRUCTURING_INVITE As Integer = 70532
        'Public Const _PGID_VISUAL_STRUCTURING_TEAMTIME As Integer = 70533
        'A1050 ==

#End Region

#Region "Surveys 7****"
        ' D0190 ===
        'Public Const _PGID_SURVEY_LIST As Integer = 70000  ' -D2780
        Public Const _PGID_SURVEY_EDIT_PRE As Integer = 79010
        Public Const _PGID_SURVEY_EDIT_POST As Integer = 79012      ' D6054
        Public Const _PGID_SURVEY_RESULTS As Integer = 79011 'L0449
        Public Const _PGID_SURVEY_QUESTION_NEW As Integer = 79020   ' L0026 + D0644
        Public Const _PGID_SURVEY_QUESTION_EDIT As Integer = 79021  ' D0226 + D0644
        Public Const _PGID_SURVEY_DOWNLOAD As Integer = 79030   ' D0297
        Public Const _PGID_SURVEY_UPLOAD As Integer = 79035     ' D1459
        Public Const _PGID_SURVEY_QUESTION_EDITOR As Integer = 79040    ' D0644
        Public Const _PGID_SURVEY_GROUP_FILTER As Integer = 79050   ' D0644
        ' D0190 ==
#End Region

#Region "Pages for Admins 8****"
        Public Const _PGID_ADMIN As Integer = 80000             ' D0089
        'Public Const _PGID_ADMIN_WELCOME As Integer = 80001     ' D0089
        Public Const _PGID_ADMIN_USERSLIST As Integer = 80010
        '-A1510 Public Const _PGID_WORKGROUP_USERSLIST As Integer = 80011 'A1495
        Public Const _PGID_ADMIN_GENERATE_USER As Integer = 80015   ' D0453
        Public Const _PGID_ADMIN_ROLEGROUPS As Integer = 80020  ' D0064
        Public Const _PGID_ADMIN_WORKGROUPS As Integer = 80030          ' D0077
        Public Const _PGID_ADMIN_WORKGROUP_CREATE As Integer = 80031    ' D0091
        Public Const _PGID_ADMIN_WORKGROUP_EDIT As Integer = 80032      ' D0091
        Public Const _PGID_ADMIN_WORKGROUP_DELETE As Integer = 80033    ' D0091
        Public Const _PGID_ADMIN_WORKGROUP_TEMPLATES As Integer = 80040 ' D0091
        Public Const _PGID_ADMIN_WORKGROUP_SAMPLES As Integer = 80045   ' D1081
        Public Const _PGID_ADMIN_WORKGROUP_WORDING_TEMPLATE As Integer = 80050 'A1113
        Public Const _PGID_ADMIN_LICENSE As Integer = 80080             ' D0257 + D3036
        Public Const _PGID_ADMIN_VIEWLOGS As Integer = 80090    ' D0168
        Public Const _PGID_ADMIN_ONLINE_USERS As Integer = 80091    ' D0181
        Public Const _PGID_ADMIN_VIEW_SIGNUP As Integer = 80092     ' D1174
        Public Const _PGID_ADMIN_LOGINS_STAT As Integer = 80095     ' D0889 + D3526
        Public Const _PGID_ADMIN_STATISTIC As Integer = 80096   ' D3526

        Public Const _PGID_ADMIN_SERVICEHASH As Integer = 80100     ' D1630
        Public Const _PGID_ADMIN_USER_INFO As Integer = 80110       ' D1643
        Public Const _PGID_ADMIN_PRJ_LOOKUP As Integer = 80111      ' D3442
        Public Const _PGID_ADMIN_PRJ_STAT As Integer = 80112        ' D3442

#End Region

#Region "Pages for Iterate workflow 88***"

        'Public Const _PGID_ITERATE_OVERVIEW As Integer = 88003
        'Public Const _PGID_ITERATE_STRUCTURING As Integer = 88001
        'Public Const _PGID_ITERATE_MEASUREMENT As Integer = 88002

        'Public Const _PGID_ITERATE_OVERVIEW_IMPACT As Integer = 88013
        'Public Const _PGID_ITERATE_STRUCTURING_IMPACT As Integer = 88011
        'Public Const _PGID_ITERATE_MEASUREMENT_IMPACT As Integer = 88012

#End Region

#Region "Service pages 9****"
        Public Const _PGID_DB_SETUP As Integer = 90001          ' D0371
        Public Const _PGID_DB_DECISIONS As Integer = 90010      ' D0371
        Public Const _PGID_DB_RESTORE As Integer = 90011        ' D0796
        Public Const _PGID_DB_SQL As Integer = 90012            ' D0921
        Public Const _PGID_SYSTEM_MESSAGE As Integer = 90020    ' D0796
        Public Const _PGID_SYSTEM_SETTINGS As Integer = 90021   ' D3821

        Public Const _PGID_ERROR_403 As Integer = 90403
        Public Const _PGID_ERROR_404 As Integer = 90404 ' D0116
        Public Const _PGID_ERROR_500 As Integer = 90500 ' D0116
        Public Const _PGID_ERROR_503 As Integer = 90503 ' D0257

        'Public Const _PGID_FEEDBACK As Integer = 90900  ' D0118    - D0883

        Public Const _PGID_JS_RESOURCES As Integer = 98001    ' D4629

        Public Const _PGID_SILVERLIGHT_UI As Integer = 99000        ' D0562
        Public Const _PGID_SERVICEPAGE As Integer = 99001   ' D0725

        'Public Const _PGID_API_ACCESS As Integer = 99901    ' D4497
        'Public Const _PGID_API_COMMON As Integer = 99902    ' D4497
        'Public Const _PGID_API_MANAGE As Integer = 99903    ' D4497

        Public Const _PGID_WEBAPI As Integer = 99900        ' D5024
        Public Const _PGID_WEBAPI_HELP As Integer = 99901   ' D7222

        'Public Const _PGID_TESt_SILVERLIGHT As Integer = 99990  ' D0529 -D1399
        Public Const _PGID_PING As Integer = 99998      ' D3987
        Public Const _PGID_TEST As Integer = 99999      ' D0326

        Public Const _PGID_UNKNOWN As Integer = -1
#End Region

#End Region

    End Module

End Namespace
